<?php
	
	if ($_COOKIE['vlang'] == 'en') { 
		$langpicjp = "lang_jp_01.png"; $langpicvn = "lang_vn_01.png"; $langpicen = "lang_en_02.png";
		$headlogo = "header_07_en.png";
		$texttitlebar = "FACT-LINK : : Japan - Vietnam Industrial Directory";
		$lb_nationality = "Company Nationality";
		$lb_njp = "Japan";
		$lb_nvn = "Vietnam";
		$lb_nkorea = "Korea";
		$lb_ntaiwan = "Taiwan";
		$lb_nhongkong = "Hongkong";
		$lb_nsingapore = "Singapore";
		$lb_nchina = "China";
		$lb_nother = "Other Nation";
		$lb_title_admin = "Admin Editor";
		$lb_en = "EN";
		$lb_jp = "JP";
		$lb_vn = "VN";
		$lb_en_full = "English Page";
		$lb_jp_full = "Japanese Page";
		$lb_vn_full = "Vietnam Page";
		$lb_back = "Back";
		$lb_enable = "Enable";
		$lb_disable = "Disable";
		$lb_alt_on = "ON (Click to set OFF)";
		$lb_alt_off = "OFF (Click to set ON)";
		$lb_alt_show = "SHOW (Click to set HIDE)";
		$lb_alt_hide = "HIDE (Click to set SHOW)";
		$lb_alt_edit = "Edit";
		$lb_alt_expand = "Add Detail";
		$lb_alt_view = "View";
		$lb_alt_create = "Create New Page";
		$lb_alt_delete = "Delete";
		$lb_alt_page = "Page Management";
		$lb_pag_name = "Menu Name";
		$lb_pag_pagetitle = "Title Bar Name";
		$lb_pag_sort = "Order No.";
		$lb_pag_textcolor = "Title Color";
		$lb_pag_title = "Title";
		$lb_pag_detail = "Detail";
		$lb_pag_image = "Image";
		$lb_pag_image_width = "Image Width (px)";
		$lb_pag_image_link = "Link to original size";
		$lb_pag_image_disable = "Disable image";
		$lb_pag_video_link = "Video link";
		$lb_pag_media_option = "Media option";
		$lb_pag_media_remove = "Remove media";
		$lb_mem_subdesc = "Company Slogan";
		$lb_mem_category = "Category";
		$lb_mem_footer = "Footer";
		$lb_prf_comname = "Company Name";
		$lb_prf_comnamejpk = "Company Name (JP Katakana)";
		$lb_prf_pername = "Representative Name";
		$lb_prf_posname = "Position";
		$lb_prf_business = "Business Description";
		$lb_prf_product = "Produce";
		$lb_prf_seocom = "Company Description (SEO)";
		$lb_prf_seokey = "Keyword (SEO)";
		$lb_prf_addlab = "Address Label";
		$lb_prf_add = "Address";
		$lb_prf_ine = "Industrial Estate";
		$lb_prf_prv = "Province";
		$lb_prf_cty = "Country";
		$lb_prf_zip = "Portal Code";
		$lb_prf_tellab = "Tel / Fax Label";
		$lb_prf_tel = "Tel / Fax";
		$lb_prf_maillab = "E-mail Label";
		$lb_prf_mail = "E-mail";
		$lb_prf_url = "Website";
		$lb_prf_establish = "Establish Date";
		$lb_prf_capital = "Capital";
		$lb_prf_parent = "Parent Company";
		$lb_prf_share = "Shareholder";
		$lb_prf_employee = "Employee";
		$lb_prf_accdate = "Account Period";
		$lb_prf_bank = "Bank";
		$lb_prf_valcus = "Value Customer";
		$lb_prf_conlab = "Content Label";
		$lb_prf_con = "Content Detail";
		$lb_pag_status = "Page Status";
		$lb_status = "Disable";
		$lb_hom_keytemplate = "Key Panel Style";
		$lb_hom_keytitlecolor = "3 Key Panel Title Color";
		$lb_hom_keytitle = "3 Key Panel Title";
		$lb_hom_keydetail = "3 Key Panel Detail";
		$lb_hom_keytitle_sub = "Key Panel Title";
		$lb_hom_keydetail_sub = "Key Panel Detail";
		$lb_hom_linetitlecolor = "3 Appeal Title Color";
		$lb_hom_linetitle = "3 Appeal Title";
		$lb_hom_linedetail = "3 Appeal Detail";
		$lb_hom_linetitle_sub = "Appeal Title";
		$lb_hom_linedetail_sub = "Appeal Detail";
		$lb_hom_lineimage = "Appeal Image";
		$lb_hom_lineimage_width = "Appeal Image Width (px)";
		$lb_hom_desc = "Bottom Note";
		$lb_con_status = "Column Status";
		$lb_con_pattern = "Column Pattern";
		$lb_con_title = "Column Title";
		$lb_con_subtitle = "Column Subtitle";
		$lb_con_titlecolor = "Column Title Color";
		$lb_ban_name = "Banner Name";
		$lb_ban_image = "Banner Image";
		$lb_ban_link = "Banner Link";
		$lb_ban_pospage = "Position - Page";
		$lb_ban_posside = "Position - Side";
		
		$lb_bul_name = "Bulletin Name";
		$lb_bul_detail = "Bulletin Text";
		$lb_bul_image = "Bulletin Image";
		$lb_bul_link = "Bulletin Link";
		
		$lb_nws_title = "News Title";
		$lb_nws_sum = "News Compend";
		$lb_nws_detail = "News Detail";
		$lb_nws_date = "News Date";
		$lb_nws_show = "Show on Top Page";
		$lb_nws_status = "Status";
		
		$lb_fea_topimage = "Top Image";
		$lb_fea_topimage_width = "Top Image Width (px)";
		$lb_fea_topdetail = "Top Detail";
		$lb_fea_image_link = "Link";
		$lb_fea_link = "Article Link";
		
		$lb_mem_tpm = "Main Template Style";
		
		$lb_username = "Username";
		$lb_password = "Password";
		$lb_password_old = "Current Password";
		$lb_password_new = "New Password";
		$lb_password_confirm = "Re-enter New Password";
		$lb_comname = "Company Name";
		$lb_ie = "Industrial Estate";
		$lb_address = "Address";
		$lb_province = "Province";
		$lb_country = "Country";
		$lb_zip = "Portal Code";
		$lb_comtel = "Tel.";
		$lb_comfax = "Fax";
		$lb_commobile = "Mobile";
		$lb_commail = "E-mail";
		$lb_contact = "Contact Name";
		$lb_position = "Contact Position";
		$lb_gender = "Gender";
		$lb_mail = "Contact E-mail";
		$lb_oth_mail = "Other Contact E-mail";
		$lb_tel = "Contact Tel.";
		$lb_confirmcode = "Confirm Code";
		$lb_confirmcode_text = "Please fill 4 digits in this box to confirm registration.";
		$lb_sort = "Sort No.";
		$lb_sortfix_text = "Fixed this member sort number.";
		$lb_male = "Male";
		$lb_female = "Female";
		$lb_left = "Left";
		$lb_right = "Right";
		$lb_register = "Register";
		$lb_memurl = "URL";
		$lb_memid = "Member ID";
		$lb_memtype = "Member Type";
		$lb_loginhis = "Login History";
		$lb_registdate = "Registered Date";
		$lb_package = "Package";
		$lb_start = "Contract Start";
		$lb_tempmain = "Main Template";
		$lb_sup_subject = "Problem";
		$lb_sup_detail = "Detail";
		$lb_subject = "Subject";
		$lb_detail = "Detail";
		$lb_date = "Date";
		$lb_link = "URL Link";
		$lb_contentname = "Content Name";
		$lb_memlist= "Member Related";
		$lb_width = "Width (px)";
		$lb_height = "Height (px)";
		$lb_name = "Name";
		$lb_memo = "Memo";
		$lb_remark = "Remark";
		$lb_panelcolor = "Panel Color";
		
		$lb_nwg_name = "Genre Name";
		$lb_nwe_name = "Editor Name";
		$lb_cate_name = "Category Name";
		$lb_cate_pos = "Level";
		$lb_cate_normal = "Normal";
		$lb_cate_main = "Main";
		$lb_cate_sub = "Sub";
		$lb_cate_under = "Sub of";
		$lb_ie_name = "I.E. Name";
		$lb_province_name = "Province Name";
		$lb_country_name = "Country Name";
		$lb_pack_name = "Package Name";
		$lb_tempmain_name = "Main Template Name";
		$lb_tempkey_name = "Key Template Name";
		$lb_clf_code = "Color Code #";
		$lb_patterncon_name = "Content Pattern Name";
		$lb_archive = "Archive";
		$lb_title = "Title";
		$lb_side = "Side";
		
		$lb_days = "Day(s)";
		$lb_months = "Month(s)";
		$lb_type = "Type";
		$lb_filename = "File Name";
		
		$lb_select = "----- Please Select -----";
		
		$tab_profile = "COMPANY PROFILE";
		$tab_home = "HOME";
		$tab_content = "CONTENT";
		$tab_presentation = "PRESENTATION";
		$tab_inquiry = "INQUIRY";
		$tab_products = "PRODUCTS";
		
		$tm_main = "Main";
		$tm_top = "Top Page";
		$tm_banner = "Banner";
		$tm_member = "Member";
		$tm_news = "News";
		$tm_contact = "Contact";
		$tm_magazine = "Magazine";
		$tm_setting = "Setting";
		
		$tt_category_sort = "Sort Category";
		$tt_member_sort = "Sort Member";
		$tt_bulletin_sort = "Sort Bulletin";
		$tt_banner_sort = "Sort Banner";
		$tt_country_sort = "Sort Country";
		
		$tt_home = "Home";
		$tt_logout = "Logout";
		$tt_memberall = "All Member List";
		$tt_memberbsc = "Basic Member List";
		$tt_memberfree = "Free Member List";
		$tt_member = "Member List";
		$tt_member_search = "Search Member";
		$tt_member_searchcate = "Search Member by Category";
		$tt_member_edit = "Edit Member";
		$tt_member_info = "Member Information";
		$tt_member_page = "Page Management";
		$tt_member_template = "Change Template";
		$tt_member_contract = "Edit Contract";
		$tt_member_bulcat = "Category Bulletin";
		$tt_member_onoff = "Change Status";
		$tt_member_inq = "Inquiry List";
		$tt_feature = "Feature Article List";
		$tt_feature_add = "Add Feature Article";
		$tt_feature_edit = "Edit Feature Article";
		$tt_feature_view = "View Feature Article";
		$tt_update = "Updated Info List";
		$tt_update_add = "Add Updated Info";
		$tt_update_edit = "Edit Updated Info";
		$tt_update_delete = "Delete Updated Info";
		$tt_introduce = "Introduce Company List";
		$tt_introduce_add = "Add Introduce Company";
		$tt_introduce_edit = "Edit Introduce Company";
		$tt_introduce_set = "Introduce Company Set List";
		$tt_introduce_set_edit = "Edit Introduce Company Set";
		$tt_news = "News List";
		$tt_news_add = "Add News";
		$tt_news_edit = "Edit News";
		$tt_news_delete = "Delete News";
		$tt_newsgenre = "News Gerne List";
		$tt_newsgenre_add = "Add News Gerne";
		$tt_newsgenre_edit = "Edit News Gerne";
		$tt_newseditor = "News Editor List";
		$tt_newseditor_add = "Add News Editor";
		$tt_newseditor_edit = "Edit News Editor";
		$tt_category = "Category List";
		$tt_category_add = "Add Category";
		$tt_category_edit = "Edit Category";
		$tt_ie = "Industrial Estate List";
		$tt_ie_add = "Add Industrial Estate";
		$tt_ie_edit = "Edit Industrial Estate";
		$tt_province = "Province List";
		$tt_province_add = "Add Province";
		$tt_province_edit = "Edit Province";
		$tt_country = "Country List";
		$tt_country_add = "Add Country";
		$tt_country_edit = "Edit Country";
		$tt_package = "Package List";
		$tt_package_add = "Add Package";
		$tt_package_edit = "Edit Package";
		$tt_tempmain = "Main Template List";
		$tt_tempmain_add = "Add Main Template";
		$tt_tempmain_edit = "Edit Main Template";
		$tt_tempkey = "Key Template List";
		$tt_tempkey_add = "Add Key Template";
		$tt_tempkey_edit = "Edit Key Template";
		$tt_fontcolor = "Font Color List";
		$tt_fontcolor_add = "Add Font Color";
		$tt_fontcolor_edit = "Edit Font Color";
		$tt_patterncon = "Content Pattern List";
		$tt_patterncon_add = "Add Content Pattern";
		$tt_patterncon_edit = "Edit Content Pattern";
		$tt_page = "Page Management";
		$tt_contact = "Contact List";
		$tt_contact_view = "View Contact";
		$tt_magazine = "Mail Magazine List";
		$tt_magazine_add = "Add Mail Magazine";
		$tt_magazine_edit = "Edit Mail Magazine";
		$tt_magazine_view = "View Mail Magazine";
		$tt_bannerspccate = "Special Banner by Category";
		$tt_bannerspc = "Special Banner List";
		$tt_bannerbsc = "Basic Banner List";
		$tt_bannerbsc2 = "Basic Banner by Category";
		$tt_banner = "Banner List";
		$tt_banner_add = "Add Banner";
		$tt_banner_edit = "Edit Banner";
		$tt_bulletin = "Bulletin List";
		$tt_bulletin_add = "Add Bulletin";
		$tt_bulletin_edit = "Edit Bulletin";
		$tt_bulletin_delete = "Delete Bulletin";
		$tt_bannercate = "Category Banner List";
		$tt_bannercate_add = "Add Category Banner";
		$tt_bannercate_edit = "Edit Category Banner";
		$tt_bulletincate = "Category Bulletin List";
		$tt_bulletincate_add = "Add Category Bulletin";
		$tt_bulletincate_edit = "Edit Category Bulletin";
		$tt_expirewarning = "Expire Warning";
		$tt_lock = "Data Locked";
		$tt_product_add = "Add Product";
		$tt_product_edit = "Edit Product";
		$lb_product_topimage = "Product Image";
		$lb_product_topimage_width = "Product Image Width";
		$lb_product_thumb_01 = "Product Thumbnail 1";
		$lb_product_thumb_02 = "Product Thumbnail 2";
		$lb_product_thumb_03 = "Product Thumbnail 3";
		$lb_product_thumb_04 = "Product Thumbnail 4";
		$lb_product_specification = "Product Specification";
		$lb_product_topdetail = "Product Detail";
		$lb_product_supplier = "Supplier";
		$tt_products_manager = "Products Manager";
		$tt_products_categorys_manager = "Products Category Manager";
		$tt_product_category = "Category List";
		$tt_product_category_add = "Add Category";
		$tt_product_category_edit = "Edit Category";
		$tm_product = "Products";

		$lb_pro_cat_des = "Category Description";
		$lb_fea_category = "Featured Category";
		$tt_fea_products_manager = "Featured Products";
		$tt_mail_products_manager = "Mail Product List";
		$tt_member_product_search = "Search Product";
		$lb_prf_product_name = "Product Name";
		$lb_prf_product_sku = "SKU";
		$tx_confirmdelete = "Are you sure to delete this?";
		$tm_events = "Events";
		$tt_event_add = "Add Event";
		$lb_event_title = "Event Title";
		$lb_event_detail = "Event Detail";
		$lb_event_status = "Status";
		$tt_oncoming_events = "Oncoming Events";
		$tt_events = "Events List";

		$mn_mailin = "Mail - Inbox";
		$lb_mail_subject = "Subject";
		$lb_mail_content = "Content";
		$lb_mail_company = "Company";
		$lb_mail_contactname = "Your Name";
		$lb_mail_tel = "TEL";
		$lb_mail_fax = "FAX";
		$lb_mail_email = "E-mail";

	} elseif ($_COOKIE['vlang'] == 'vn') {

		$langpicjp = "lang_jp_01.png"; $langpicvn = "lang_vn_02.png"; $langpicen = "lang_en_01.png";
		$headlogo = "header_07_vn.png";
		$texttitlebar = "FACT-LINK : : Cổng thông tin dành cho các doanh nghiệp Nhật Bản và Việt Nam";
		
		$lb_nationality = "Company Nationality";
		$lb_njp = "Japan";
		$lb_nvn = "Vietnam";
		$lb_nkorea = "Korea";
		$lb_ntaiwan = "Taiwan";
		$lb_nhongkong = "Hongkong";
		$lb_nsingapore = "Singapore";
		$lb_nchina = "China";
		$lb_nother = "Other Nation";
		
		$lb_title_admin = "Bộ soạn thảo của admin";
		
		$lb_en = "EN";
		$lb_jp = "JP";
		$lb_vn = "VN";
		$lb_en_full = "English Page";
		$lb_jp_full = "Japanese Page";
		$lb_vn_full = "Vietnam Page";
		$lb_back = "Back";
		$lb_enable = "Enable";
		$lb_disable = "Disable";
		
		$lb_alt_on = "ON (Click to set OFF)";
		$lb_alt_off = "OFF (Click to set ON)";
		$lb_alt_show = "SHOW (Click to set HIDE)";
		$lb_alt_hide = "HIDE (Click to set SHOW)";
		$lb_alt_edit = "Edit";
		$lb_alt_expand = "Add Detail";
		$lb_alt_view = "View";
		$lb_alt_create = "Create New Page";
		$lb_alt_delete = "Delete";
		$lb_alt_page = "Page Management";
		
		$lb_pag_name = "Menu Name";
		$lb_pag_pagetitle = "Title Bar Name";
		$lb_pag_sort = "Order No.";
		$lb_pag_textcolor = "Title Color";
		$lb_pag_title = "Title";
		$lb_pag_detail = "Detail";
		$lb_pag_image = "Image";
		$lb_pag_image_width = "Image Width (px)";
		$lb_pag_image_link = "Link to original size";
		$lb_pag_image_disable = "Disable image";
		$lb_pag_video_link = "Video link";
		$lb_pag_media_option = "Media option";
		$lb_pag_media_remove = "Remove media";
		$lb_mem_subdesc = "Company Slogan";
		$lb_mem_category = "Category";
		$lb_mem_footer = "Footer";
		$lb_prf_comname = "Company Name";
		$lb_prf_comnamejpk = "Company Name (JP Katakana)";
		$lb_prf_pername = "Representative Name";
		$lb_prf_posname = "Position";
		$lb_prf_business = "Business Description";
		$lb_prf_product = "Produce";
		$lb_prf_seocom = "Company Description (SEO)";
		$lb_prf_seokey = "Keyword (SEO)";
		$lb_prf_addlab = "Address Label";
		$lb_prf_add = "Address";
		$lb_prf_ine = "Industrial Estate";
		$lb_prf_prv = "Province";
		$lb_prf_cty = "Country";
		$lb_prf_zip = "Portal Code";
		$lb_prf_tellab = "Tel / Fax Label";
		$lb_prf_tel = "Tel / Fax";
		$lb_prf_maillab = "E-mail Label";
		$lb_prf_mail = "E-mail";
		$lb_prf_url = "Website";
		$lb_prf_establish = "Establish Date";
		$lb_prf_capital = "Capital";
		$lb_prf_parent = "Parent Company";
		$lb_prf_share = "Shareholder";
		$lb_prf_employee = "Employee";
		$lb_prf_accdate = "Account Period";
		$lb_prf_bank = "Bank";
		$lb_prf_valcus = "Value Customer";
		$lb_prf_conlab = "Content Label";
		$lb_prf_con = "Content Detail";
		
		$lb_pag_status = "Page Status";
		$lb_status = "Disable";
		$lb_hom_keytemplate = "Key Panel Style";
		$lb_hom_keytitlecolor = "3 Key Panel Title Color";
		$lb_hom_keytitle = "3 Key Panel Title";
		$lb_hom_keydetail = "3 Key Panel Detail";
		$lb_hom_keytitle_sub = "Key Panel Title";
		$lb_hom_keydetail_sub = "Key Panel Detail";
		$lb_hom_linetitlecolor = "3 Appeal Title Color";
		$lb_hom_linetitle = "3 Appeal Title";
		$lb_hom_linedetail = "3 Appeal Detail";
		$lb_hom_linetitle_sub = "Appeal Title";
		$lb_hom_linedetail_sub = "Appeal Detail";
		$lb_hom_lineimage = "Appeal Image";
		$lb_hom_lineimage_width = "Appeal Image Width (px)";
		$lb_hom_desc = "Bottom Note";
		
		$lb_con_status = "Column Status";
		$lb_con_pattern = "Column Pattern";
		$lb_con_title = "Column Title";
		$lb_con_subtitle = "Column Subtitle";
		$lb_con_titlecolor = "Column Title Color";
		
		$lb_ban_name = "Banner Name";
		$lb_ban_image = "Banner Image";
		$lb_ban_link = "Banner Link";
		$lb_ban_pospage = "Position - Page";
		$lb_ban_posside = "Position - Side";
		
		$lb_bul_name = "Bulletin Name";
		$lb_bul_detail = "Bulletin Text";
		$lb_bul_image = "Bulletin Image";
		$lb_bul_link = "Bulletin Link";
		
		$lb_nws_title = "News Title";
		$lb_nws_sum = "News Compend";
		$lb_nws_detail = "News Detail";
		$lb_nws_date = "News Date";
		$lb_nws_show = "Show on Top Page";
		$lb_nws_status = "Status";
		
		$lb_fea_topimage = "Top Image";
		$lb_fea_topimage_width = "Top Image Width (px)";
		$lb_fea_topdetail = "Top Detail";
		$lb_fea_image_link = "Link";
		$lb_fea_link = "Article Link";
		
		$lb_mem_tpm = "Main Template Style";
		
		$lb_username = "Username";
		$lb_password = "Password";
		$lb_password_old = "Current Password";
		$lb_password_new = "New Password";
		$lb_password_confirm = "Re-enter New Password";
		$lb_comname = "Company Name";
		$lb_ie = "Industrial Estate";
		$lb_address = "Address";
		$lb_province = "Province";
		$lb_country = "Country";
		$lb_zip = "Portal Code";
		$lb_comtel = "Tel.";
		$lb_comfax = "Fax";
		$lb_commobile = "Mobile";
		$lb_commail = "E-mail";
		$lb_contact = "Contact Name";
		$lb_position = "Contact Position";
		$lb_gender = "Gender";
		$lb_mail = "Contact E-mail";
		$lb_oth_mail = "Other Contact E-mail";
		$lb_tel = "Contact Tel.";
		$lb_confirmcode = "Confirm Code";
		$lb_confirmcode_text = "Please fill 4 digits in this box to confirm registration.";
		$lb_sort = "Sort No.";
		$lb_sortfix_text = "Fixed this member sort number.";
		$lb_male = "Male";
		$lb_female = "Female";
		$lb_left = "Left";
		$lb_right = "Right";
		$lb_register = "Register";
		$lb_memurl = "URL";
		$lb_memid = "Member ID";
		$lb_memtype = "Member Type";
		$lb_loginhis = "Login History";
		$lb_registdate = "Registered Date";
		$lb_package = "Package";
		$lb_start = "Contract Start";
		$lb_tempmain = "Main Template";
		$lb_sup_subject = "Problem";
		$lb_sup_detail = "Detail";
		$lb_subject = "Subject";
		$lb_detail = "Detail";
		$lb_date = "Date";
		$lb_link = "URL Link";
		$lb_contentname = "Content Name";
		$lb_memlist= "Member Related";
		$lb_width = "Width (px)";
		$lb_height = "Height (px)";
		$lb_name = "Name";
		$lb_memo = "Memo";
		$lb_remark = "Remark";
		$lb_panelcolor = "Panel Color";
		
		$lb_nwg_name = "Genre Name";
		$lb_nwe_name = "Editor Name";
		$lb_cate_name = "Category Name";
		$lb_cate_pos = "Level";
		$lb_cate_normal = "Normal";
		$lb_cate_main = "Main";
		$lb_cate_sub = "Sub";
		$lb_cate_under = "Sub of";
		$lb_ie_name = "I.E. Name";
		$lb_province_name = "Province Name";
		$lb_country_name = "Country Name";
		$lb_pack_name = "Package Name";
		$lb_tempmain_name = "Main Template Name";
		$lb_tempkey_name = "Key Template Name";
		$lb_clf_code = "Color Code #";
		$lb_patterncon_name = "Content Pattern Name";
		$lb_archive = "Archive";
		$lb_title = "Title";
		$lb_side = "Side";
		
		$lb_days = "Day(s)";
		$lb_months = "Month(s)";
		$lb_type = "Type";
		$lb_filename = "File Name";
		
		$lb_select = "----- Please Select -----";
		
		$tab_profile = "COMPANY PROFILE";
		$tab_home = "HOME";
		$tab_content = "CONTENT";
		$tab_presentation = "PRESENTATION";
		$tab_inquiry = "INQUIRY";
		$tab_products = "PRODUCTS";
		
		$tm_main = "Trang chính";
		$tm_top = "Đầu trang";
		$tm_banner = "Banner";
		$tm_member = "Thành viên";
		$tm_news = "Tin tức";
		$tm_contact = "Liên hệ";
		$tm_magazine = "Tạp chí";
		$tm_setting = "Thiết lập";
		
		$tt_category_sort = "Sort Category";
		$tt_member_sort = "Sort Member";
		$tt_bulletin_sort = "Sort Bulletin";
		$tt_banner_sort = "Sort Banner";
		$tt_country_sort = "Sort Country";
		
		$tt_home = "Trang chủ";
		$tt_logout = "Đăng xuất";
		$tt_memberall = "Tất cả danh sách thành viên";
		$tt_memberbsc = "Danh sách thành viên cơ bản";
		$tt_memberfree = "Danh sách thành viên miễn phí";
		$tt_member = "Danh sách thành viên";
		$tt_member_search = "Tìm kiếm thành viên";
		$tt_member_searchcate = "Tìm kiếm thành viên theo danh mục";
		$tt_member_edit = "Chỉnh sửa thành viên";
		$tt_member_info = "Thông tin thành viên";
		$tt_member_page = "Quản lý trang";
		$tt_member_template = "Giao diện";
		$tt_member_contract = "Chỉnh sửa hợp đồng";
		$tt_member_bulcat = "Mục bản tin";
		$tt_member_onoff = "Thay đổi trạng thái";
		$tt_member_inq = "Danh sách yêu cầu";
		$tt_feature = "Danh sách bài viết nổi bật";
		$tt_feature_add = "Thêm bài viết nổi bật";
		$tt_feature_edit = "Chỉnh sửa bài viết nổi bật";
		$tt_feature_view = "Xem bài viết nổi bật";
		$tt_update = "Danh sách thông tin được cập nhật";
		$tt_update_add = "Thêm thông tin được cập nhật";
		$tt_update_edit = "Chỉnh sửa thông tin được cập nhật";
		$tt_update_delete = "Xóa thông tin được cập nhật";
		$tt_introduce = "Giới thiệu công ty";
		$tt_introduce_add = "Thêm giới thiệu công ty";
		$tt_introduce_edit = "Chỉnh sửa giới thiệu công ty";
		$tt_introduce_set = "Danh sách tập hợp giới thiệu công ty";
		$tt_introduce_set_edit = "Chỉnh sửa tập hợp giới thiệu công ty";
		$tt_news = "Thêm danh sách";
		$tt_news_add = "Thêm tin tức";
		$tt_news_edit = "Chỉnh sửa tin tức";
		$tt_news_delete = "Xóa tin tức";
		$tt_newsgenre = "Danh sách loại tin tức";
		$tt_newsgenre_add = "Thêm loại tin tức";
		$tt_newsgenre_edit = "Chỉnh sửa loại tin tức";
		$tt_newseditor = "Danh sách người biên tập";
		$tt_newseditor_add = "Thêm người biên tập";
		$tt_newseditor_edit = "Chỉnh sửa người biên tập";
		$tt_category = "Danh sách các danh mục";
		$tt_category_add = "Thêm danh mục";
		$tt_category_edit = "Chỉnh sửa danh mục";
		$tt_ie = "Danh sách khu công nghiệp";
		$tt_ie_add = "Thêm khu công nghiệp";
		$tt_ie_edit = "Chỉnh sửa khu công nghiệp";
		$tt_province = "Danh sách tỉnh thành";
		$tt_province_add = "Thêm tỉnh thành";
		$tt_province_edit = "Chỉnh sửa tỉnh thành";
		$tt_country = "Danh sách quốc gia";
		$tt_country_add = "Thêm quốc gia";
		$tt_country_edit = "Chỉnh sửa quốc gia";
		$tt_package = "Danh sách gói";
		$tt_package_add = "Thêm gói";
		$tt_package_edit = "Chỉnh sửa gói";
		$tt_tempmain = "Main Template List";
		$tt_tempmain_add = "Add Main Template";
		$tt_tempmain_edit = "Edit Main Template";
		$tt_tempkey = "Key Template List";
		$tt_tempkey_add = "Add Key Template";
		$tt_tempkey_edit = "Edit Key Template";
		$tt_fontcolor = "Font Color List";
		$tt_fontcolor_add = "Add Font Color";
		$tt_fontcolor_edit = "Edit Font Color";
		$tt_patterncon = "Content Pattern List";
		$tt_patterncon_add = "Add Content Pattern";
		$tt_patterncon_edit = "Edit Content Pattern";
		$tt_page = "Quản lý trang";
		$tt_contact = "Danh sách liên lạc";
		$tt_contact_view = "Xem liên lạc";
		$tt_magazine = "Mail Magazine List";
		$tt_magazine_add = "Add Mail Magazine";
		$tt_magazine_edit = "Edit Mail Magazine";
		$tt_magazine_view = "View Mail Magazine";
		$tt_bannerspccate = "Banner đặc biệt theo mục";
		$tt_bannerspc = "Danh sách banner đặc biệt";
		$tt_bannerbsc = "Danh sách banner cơ bản";
		$tt_bannerbsc2 = "Basic Banner by Category";
		$tt_banner = "Danh sách banner";
		$tt_banner_add = "Thêm banner";
		$tt_banner_edit = "Chỉnh sửa banner";
		$tt_bulletin = "Danh sách bản tin";
		$tt_bulletin_add = "Thêm bản tin";
		$tt_bulletin_edit = "Chỉnh sửa bản tin";
		$tt_bulletin_delete = "Xóa bản tin";
		$tt_bannercate = "Danh sách mục banner";
		$tt_bannercate_add = "Thêm sửa mục banner";
		$tt_bannercate_edit = "Chỉnh sửa mục banner";
		$tt_bulletincate = "Danh sách mục bản tin";
		$tt_bulletincate_add = "Thêm mục bản tin";
		$tt_bulletincate_edit = "Chỉnh sửa mục bản tin";
		$tt_expirewarning = "Cảnh báo hết hiệu lực";
		$tt_lock = "Dữ liệu đã bị khóa";
		$tt_product_add = "Thêm sản phẩm";
		$tt_product_edit = "Chỉnh sửa sản phẩm";
		$lb_product_topimage = "Product Image";
		$lb_product_topimage_width = "Product Image Width";
		$lb_product_thumb_01 = "Product Thumbnail 1";
		$lb_product_thumb_02 = "Product Thumbnail 2";
		$lb_product_thumb_03 = "Product Thumbnail 3";
		$lb_product_thumb_04 = "Product Thumbnail 4";
		$lb_product_topdetail = "Product Detail";
		$lb_product_supplier = "Supplier";
		$tt_products_manager = "Products Manager";
		$tt_products_categorys_manager = "Products Category Manager";
		$tt_product_category = "Category List";
		$lb_pro_cat_des = "Category Description";
		$lb_fea_category = "Featured Category";
		$tt_fea_products_manager = "Featured Products";
		$tm_product = "Products";
		$tt_product_category_edit = "Edit Category";
		
		$tx_confirmdelete = "Bạn có chắc muốn xóa?"; 
		$lb_product_topimage = "Product Image";
		$lb_product_specification = "Product Specification";
		$tt_product_category_add = "Add Category";
		$tt_mail_products_manager = "Mail Product List";
		$tt_member_product_search = "Search Product";
		$lb_prf_product_name = "Product Name";
		$lb_prf_product_sku = "SKU";
		$tm_events = "Events";
		$tt_event_add = "Add Event";
		$lb_event_title = "Event Title";
		$lb_event_detail = "Event Detail";
		$lb_event_status = "Status";
		$tt_oncoming_events = "Oncoming Events";
		$tt_events = "Events List";

		$mn_mailin = "Hộp thư đến";
		$lb_mail_subject = "Tiêu đề";
		$lb_mail_content = "Nội dung";
		$lb_mail_company = "Công ty";
		$lb_mail_contactname = "Tên của bạn";
		$lb_mail_tel = "Số điện thoại";
		$lb_mail_fax = "Số fax";
		$lb_mail_email = "Địa chỉ mail";
	} else {

		$langpicjp = "lang_jp_02.png"; $langpicvn = "lang_vn_01.png"; $langpicen = "lang_en_01.png";
		$headlogo = "header_07_jp.png";
		$texttitlebar = "FACT-LINK : : ベトナムの日系製造業のためのポータルサイト";
		
		$lb_nationality = "Company Nationality";
		$lb_njp = "Japan";
		$lb_nvn = "Vietnam";
		$lb_nkorea = "Korea";
		$lb_ntaiwan = "Taiwan";
		$lb_nhongkong = "Hongkong";
		$lb_nsingapore = "Singapore";
		$lb_nchina = "China";
		$lb_nother = "Other Nation";
		
		$lb_title_admin = "管理編集";
		
		$lb_en = "英語";
		$lb_jp = "日本語";
		$lb_vn = "ベトナム語";
		$lb_en_full = "英語のページ";
		$lb_jp_full = "日本語のページ";
		$lb_vn_full = "ベトナム語のページ";
		$lb_back = "戻る";
		$lb_enable = "有効にする";
		$lb_disable = "無効にする";
		
		$lb_alt_on = "ON (Click to set OFF)";
		$lb_alt_off = "OFF (Click to set ON)";
		$lb_alt_show = "SHOW (Click to set HIDE)";
		$lb_alt_hide = "HIDE (Click to set SHOW)";
		$lb_alt_edit = "Edit";
		$lb_alt_expand = "Add Detail";
		$lb_alt_view = "View";
		$lb_alt_create = "Create New Page";
		$lb_alt_delete = "Delete";
		$lb_alt_page = "Page Management";
		
		$lb_pag_name = "メニューに表示する名称";
		$lb_pag_pagetitle = "ブラウザに表示する名称";
		$lb_pag_sort = "メニュー並び順";
		$lb_pag_textcolor = "大見出しの色";
		$lb_pag_title = "ページの大見出し";
		$lb_pag_detail = "一番上の文章";
		$lb_pag_image = "一番上の写真";
		$lb_pag_image_width = "横幅 (px)";
		$lb_pag_image_link = "元の画像にリンクを張る";
		$lb_pag_image_disable = "掲載の画像を削除する";
		$lb_pag_video_link = "動画のリンク";
		$lb_pag_media_option = "メディアオプション";
		$lb_pag_media_remove = "メディアを削除する";
		$lb_mem_subdesc = "会社キャッチコピー";
		$lb_mem_category = "業種別";
		$lb_mem_footer = "下部欄外の帯名称";
		$lb_prf_comname = "会社名";
		$lb_prf_comnamejpk = "会社名（カタカナ）";
		$lb_prf_pername = "代表者名";
		$lb_prf_posname = "役職";
		$lb_prf_business = "事業内容";
		$lb_prf_product = "取扱品目";
		$lb_prf_seocom = "会社の説明（検索＆SEO用）";
		$lb_prf_seokey = "キーワード（検索＆SEO用）";
		$lb_prf_addlab = "住所（見出し）";
		$lb_prf_add = "住所";
		$lb_prf_ine = "住所（工業団地）";
		$lb_prf_prv = "住所（県名）";
		$lb_prf_cty = "住所（国名）";
		$lb_prf_zip = "住所（郵便番号）";
		$lb_prf_tellab = "電話（見出し）";
		$lb_prf_tel = "電話";
		$lb_prf_maillab = "E-mail（見出し）";
		$lb_prf_mail = "E-mail";
		$lb_prf_url = "URL";
		$lb_prf_establish = "創立日";
		$lb_prf_capital = "資本金";
		$lb_prf_parent = "親会社";
		$lb_prf_share = "主要株主";
		$lb_prf_employee = "従業員数";
		$lb_prf_accdate = "決算期";
		$lb_prf_bank = "取引銀行";
		$lb_prf_valcus = "主要取引先";
		$lb_prf_conlab = "内容（見出し）";
		$lb_prf_con = "内容";
		
		$lb_pag_status = "ページ表示/非表示";
		$lb_status = "非表示";
		$lb_hom_keytemplate = "パネル様式";
		$lb_hom_keytitlecolor = "３連パネルの大見出しの色";
		$lb_hom_keytitle = "３連パネルの大見出し";
		$lb_hom_keydetail = "３連パネルの説明文";
		$lb_hom_keytitle_sub = "パネル：題名";
		$lb_hom_keydetail_sub = "パネル：文章";
		$lb_hom_linetitlecolor = "３連アピールの大見出し";
		$lb_hom_linetitle = "３連アピールの大見出しの色";
		$lb_hom_linedetail = "３連アピールの説明文";
		$lb_hom_linetitle_sub = "アピール：題名";
		$lb_hom_linedetail_sub = "アピール：文章";
		$lb_hom_lineimage = "アピール：写真";
		$lb_hom_lineimage_width = "アピール：写真横幅 (px)";
		$lb_hom_desc = "一番下の文（注記など）";
		
		$lb_con_status = "表示/非表示";
		$lb_con_pattern = "デザイン選択";
		$lb_con_title = "タイトル";
		$lb_con_subtitle = "サブタイトル";
		$lb_con_titlecolor = "タイトルの色";
		
		$lb_ban_name = "Banner Name";
		$lb_ban_image = "Banner Image";
		$lb_ban_link = "Banner Link";
		$lb_ban_pospage = "Position - Page";
		$lb_ban_posside = "Position - Side";
		
		$lb_bul_name = "Bulletin Name";
		$lb_bul_detail = "Bulletin Text";
		$lb_bul_image = "Bulletin Image";
		$lb_bul_link = "Bulletin Link";
		
		$lb_nws_title = "News Title";
		$lb_nws_sum = "News Compend";
		$lb_nws_detail = "News Detail";
		$lb_nws_date = "News Date";
		$lb_nws_show = "Show on Top Page";
		$lb_nws_status = "Status";
		
		$lb_fea_topimage = "Top Image";
		$lb_fea_topimage_width = "Top Image Width (px)";
		$lb_fea_topdetail = "Top Detail";
		$lb_fea_image_link = "Link";
		$lb_fea_link = "Article Link";
		
		$lb_mem_tpm = "デザイン選択";
		
		$lb_username = "希望ユーザー名";
		$lb_password = "初期パスワード";
		$lb_password_old = "現在のパスワード";
		$lb_password_new = "新しいパスワード";
		$lb_password_confirm = "パスワード再入力";
		$lb_comname = "会社名";
		$lb_ie = "工業団地";
		$lb_address = "住所";
		$lb_province = "県名";
		$lb_country = "国名";
		$lb_zip = "郵便番号";
		$lb_comtel = "TEL";
		$lb_comfax = "FAX";
		$lb_commobile = "MOBILE";
		$lb_commail = "E-MAIL";
		$lb_contact = "担当者";
		$lb_position = "部署役職名";
		$lb_gender = "性別";
		$lb_mail = "ご連絡先 E-MAIL";
		$lb_oth_mail = "Other Contact E-mail";
		$lb_tel = "ご連絡先 TEL";
		$lb_confirmcode = "Confirm Code";
		$lb_confirmcode_text = "Please fill 4 digits in this box to confirm registration.";
		$lb_sort = "Sort No.";
		$lb_sortfix_text = "Fixed this member sort number.";
		$lb_male = "男性";
		$lb_female = "女性";
		$lb_left = "左";
		$lb_right = "右";
		$lb_register = "確認画面へ進む";
		$lb_memurl = "URL";
		$lb_memid = "会員番号";
		$lb_memtype = "会員区分";
		$lb_loginhis = "ログイン";
		$lb_registdate = "Registered Date";
		$lb_package = "Package";
		$lb_start = "Contract Start";
		$lb_tempmain = "Main Template";
		$lb_sup_subject = "題名";
		$lb_sup_detail = "本文";
		$lb_subject = "Subject";
		$lb_detail = "Detail";
		$lb_date = "Date";
		$lb_link = "URL Link";
		$lb_contentname = "Content Name";
		$lb_memlist= "Member Related";
		$lb_width = "Width (px)";
		$lb_height = "Height (px)";
		$lb_name = "名称";
		$lb_memo = "覚え書き";
		$lb_remark = "備考";
		$lb_panelcolor = "Panel Color";
		
		$lb_nwg_name = "Genre Name";
		$lb_nwe_name = "Editor Name";
		$lb_cate_name = "Category Name";
		$lb_cate_pos = "Level";
		$lb_cate_normal = "Normal";
		$lb_cate_main = "Main";
		$lb_cate_sub = "Sub";
		$lb_cate_under = "Sub of";
		$lb_ie_name = "I.E. Name";
		$lb_province_name = "Province Name";
		$lb_country_name = "Country Name";
		$lb_pack_name = "Package Name";
		$lb_tempmain_name = "Main Template Name";
		$lb_tempkey_name = "Key Template Name";
		$lb_clf_code = "Color Code #";
		$lb_patterncon_name= "Content Pattern Name";
		$lb_archive = "書庫";
		$lb_title = "Title";
		$lb_side = "Side";
		
		$lb_days = "Day(s)";
		$lb_months = "Month(s)";
		$lb_type = "Type";
		$lb_filename = "File Name";
		
		$lb_select = "----- Please Select -----";
		
		$tab_profile = "COMPANY PROFILE";
		$tab_home = "HOME";
		$tab_content = "CONTENT";
		$tab_presentation = "PRESENTATION";
		$tab_inquiry = "INQUIRY";
		$tab_products = "PRODUCTS";
		
		$tm_main = "メイン";
		$tm_top = "トップページ";
		$tm_banner = "バナー";
		$tm_member = "メンバー";
		$tm_news = "ニュース";
		$tm_contact = "連絡";
		$tm_magazine = "マガジン";
		$tm_setting = "設定";
		
		$tt_category_sort = "Sort Category";
		$tt_member_sort = "Sort Member";
		$tt_bulletin_sort = "Sort Bulletin";
		$tt_banner_sort = "Sort Banner";
		$tt_country_sort = "Sort Country";
		
		$tt_home = "ホーム";
		$tt_logout = "ログアウト";
		$tt_memberall = "会員リスト";
		$tt_memberbsc = "Basic Member List";
		$tt_memberfree = "Free Member List";
		$tt_member = "会員リスト";
		$tt_member_search = "会員検索";
		$tt_member_searchcate = "業種別会員検索";
		$tt_member_edit = "Edit Member";
		$tt_member_info = "Member Information";
		$tt_member_page = "Page Management";
		$tt_member_template = "Change Template";
		$tt_member_contract = "Edit Contract";
		$tt_member_bulcat = "Category Bulletin";
		$tt_member_onoff = "Change Status";
		$tt_member_inq = "Inquiry List";
		$tt_feature = "特集記事";
		$tt_feature_add = "Add Feature Article";
		$tt_feature_edit = "Edit Feature Article";
		$tt_feature_view = "View Feature Article";
		$tt_update = "最新情報";
		$tt_update_add = "Add Updated Info";
		$tt_update_edit = "Edit Updated Info";
		$tt_update_delete = "Delete Updated Info";
		$tt_introduce = "企業紹介(一押し企業)";
		$tt_introduce_add = "Add Introduce Company";
		$tt_introduce_edit = "Edit Introduce Company";
		$tt_introduce_set = "企業紹介設定(一押し企業)";
		$tt_introduce_set_edit = "Edit Introduce Company Set";
		$tt_news = "ニュース";
		$tt_news_add = "Add News";
		$tt_news_edit = "Edit News";
		$tt_news_delete = "Delete News";
		$tt_newsgenre = "ニュースジャンル";
		$tt_newsgenre_add = "Add News Gerne";
		$tt_newsgenre_edit = "Edit News Gerne";
		$tt_newseditor = "ニュース編集";
		$tt_newseditor_add = "Add News Editor";
		$tt_newseditor_edit = "Edit News Editor";
		$tt_category = "業種別リスト";
		$tt_category_add = "Add Category";
		$tt_category_edit = "Edit Category";
		$tt_ie = "工業団地別リスト";
		$tt_ie_add = "Add Industrial Estate";
		$tt_ie_edit = "Edit Industrial Estate";
		$tt_province = "地域別リスト";
		$tt_province_add = "Add Province";
		$tt_province_edit = "Edit Province";
		$tt_country = "国別リスト";
		$tt_country_add = "Add Country";
		$tt_country_edit = "Edit Country";
		$tt_package = "パッケージ";
		$tt_package_add = "Add Package";
		$tt_package_edit = "Edit Package";
		$tt_tempmain = "メインテンプレート";
		$tt_tempmain_add = "Add Main Template";
		$tt_tempmain_edit = "Edit Main Template";
		$tt_tempkey = "キーテンプレート";
		$tt_tempkey_add = "Add Key Template";
		$tt_tempkey_edit = "Edit Key Template";
		$tt_fontcolor = "フォントカラー";
		$tt_fontcolor_add = "Add Font Color";
		$tt_fontcolor_edit = "Edit Font Color";
		$tt_patterncon = "Content Pattern List";
		$tt_patterncon_add = "Add Content Pattern";
		$tt_patterncon_edit = "Edit Content Pattern";
		$tt_page = "Page Management";
		$tt_contact = "連絡事項";
		$tt_contact_view = "View Contact";
		$tt_magazine = "メールマガジン";
		$tt_magazine_add = "Add Mail Magazine";
		$tt_magazine_edit = "Edit Mail Magazine";
		$tt_magazine_view = "View Mail Magazine";
		$tt_bannerspccate = "業種別スペシャルバナー";
		$tt_bannerspc = "スペシャルバナー";
		$tt_bannerbsc = "ベーシックバナー";
		$tt_bannerbsc2 = "Basic Banner by Category";
		$tt_banner = "バナーレート";
		$tt_banner_add = "Add Banner";
		$tt_banner_edit = "Edit Banner";
		$tt_bulletin = "告示";
		$tt_bulletin_add = "Add Bulletin";
		$tt_bulletin_edit = "Edit Bulletin";
		$tt_bulletin_delete = "Delete Bulletin";
		$tt_bannercate = "Category Banner List";
		$tt_bannercate_add = "Add Category Banner";
		$tt_bannercate_edit = "Edit Category Banner";
		$tt_bulletincate = "Category Bulletin List";
		$tt_bulletincate_add = "Add Category Bulletin";
		$tt_bulletincate_edit = "Edit Category Bulletin";
		$tt_expirewarning = "Expire Warning";
		$tt_lock = "現在使用中";
		$tt_product_add = "Add Product";
		$tt_product_edit = "Edit Product";
		$lb_product_topimage_width = "Product Image Width";
		$lb_product_topimage = "Product Image";
		$lb_product_topimage = "Product Image";
		$lb_product_thumb_01 = "Product Thumbnail 1";
		$lb_product_thumb_02 = "Product Thumbnail 2";
		$lb_product_thumb_03 = "Product Thumbnail 3";
		$lb_product_thumb_04 = "Product Thumbnail 4";
		$lb_product_specification = "Product Specification";
		$lb_product_topdetail = "Product Detail";
		$lb_product_supplier = "Supplier";
		$tt_products_manager = "Products Manager";
		$tt_products_categorys_manager = "Products Category Manager";
		$tt_product_category = "Category List";
		$tt_product_category_add = "Add Category";
		$lb_pro_cat_des = "Category Description";
		$lb_fea_category = "Featured Category";
		$tt_fea_products_manager = "Featured Products";
		$tm_product = "Products";
		$tt_mail_products_manager = "Mail Product List";
		$tt_member_product_search = "Search Product";
		$lb_prf_product_name = "Product Name";
		$lb_prf_product_sku = "SKU";
		$tt_product_category_edit = "Edit Category";
		$tx_confirmdelete = "Are you sure to delete this?";
		$tm_events = "Events";
		$tt_event_add = "Add Event";
		$lb_event_title = "Event Title";
		$lb_event_detail = "Event Detail";
		$lb_event_status = "Status";
		$tt_oncoming_events = "Oncoming Events";
		$tt_events = "Events List";

		$mn_mailin = "メール - 受信";
		$lb_mail_subject = "題名";
		$lb_mail_content = "内容";
		$lb_mail_company = "貴社名";
		$lb_mail_contactname = "お名前";
		$lb_mail_tel = "TEL";
		$lb_mail_fax = "FAX";
		$lb_mail_email = "メールアドレス";
	} 
	
	$tpl->assign("##langpicjp##", $langpicjp);
	$tpl->assign("##langpicvn##", $langpicvn);
	$tpl->assign("##langpicen##", $langpicen);
	$tpl->assign("##headlogo##", $headlogo);
	$tpl->assign("##texttitlebar##", $texttitlebar);
	$tpl->assign("##lb_nationality##", $lb_nationality);
	$tpl->assign("##lb_njp##", $lb_njp);
	$tpl->assign("##lb_nvn##", $lb_nvn);
	$tpl->assign("##lb_nkorea##", $lb_nkorea);
	$tpl->assign("##lb_ntaiwan##", $lb_ntaiwan);
	$tpl->assign("##lb_nhongkong##", $lb_nhongkong);
	$tpl->assign("##lb_nsingapore##", $lb_nsingapore);
	$tpl->assign("##lb_nchina##", $lb_nchina);
	$tpl->assign("##lb_nother##", $lb_nother);
	$tpl->assign("##lb_title_admin##", $lb_title_admin);
	$tpl->assign("##lb_en##", $lb_en);
	$tpl->assign("##lb_jp##", $lb_jp);
	$tpl->assign("##lb_vn##", $lb_vn);
	$tpl->assign("##lb_en_full##", $lb_en_full);
	$tpl->assign("##lb_jp_full##", $lb_jp_full);
	$tpl->assign("##lb_vn_full##", $lb_vn_full);
	$tpl->assign("##lb_back##", $lb_back);
	$tpl->assign("##lb_enable##", $lb_enable);
	$tpl->assign("##lb_disable##", $lb_disable);
	$tpl->assign("##lb_alt_edit##", $lb_alt_edit);
	$tpl->assign("##lb_alt_expand##", $lb_alt_expand);
	$tpl->assign("##lb_alt_view##", $lb_alt_view);
	$tpl->assign("##lb_alt_create##", $lb_alt_create);
	$tpl->assign("##lb_alt_delete##", $lb_alt_delete);
	$tpl->assign("##lb_alt_page##", $lb_alt_page);
	$tpl->assign("##lb_pag_name##", $lb_pag_name);
	$tpl->assign("##lb_pag_pagetitle##", $lb_pag_pagetitle);
	$tpl->assign("##lb_pag_sort##", $lb_pag_sort);
	$tpl->assign("##lb_pag_textcolor##", $lb_pag_textcolor);
	$tpl->assign("##lb_pag_title##", $lb_pag_title);
	$tpl->assign("##lb_pag_detail##", $lb_pag_detail);
	$tpl->assign("##lb_pag_image##", $lb_pag_image);
	$tpl->assign("##lb_pag_image_width##", $lb_pag_image_width);
	$tpl->assign("##lb_pag_image_link##", $lb_pag_image_link);
	$tpl->assign("##lb_pag_image_disable##", $lb_pag_image_disable);
	$tpl->assign("##lb_pag_video_link##", $lb_pag_video_link);
	$tpl->assign("##lb_pag_media_option##", $lb_pag_media_option);
	$tpl->assign("##lb_pag_media_remove##", $lb_pag_media_remove);
	$tpl->assign("##lb_mem_subdesc##", $lb_mem_subdesc);
	$tpl->assign("##lb_mem_category##", $lb_mem_category);
	$tpl->assign("##lb_mem_footer##", $lb_mem_footer);
	$tpl->assign("##lb_prf_comname##", $lb_prf_comname);
	$tpl->assign("##lb_prf_pername##", $lb_prf_pername);
	$tpl->assign("##lb_prf_posname##", $lb_prf_posname);
	$tpl->assign("##lb_prf_business##", $lb_prf_business);
	$tpl->assign("##lb_prf_product##", $lb_prf_product);
	$tpl->assign("##lb_prf_seocom##", $lb_prf_seocom);
	$tpl->assign("##lb_prf_seokey##", $lb_prf_seokey);
	$tpl->assign("##lb_prf_addlab##", $lb_prf_addlab);
	$tpl->assign("##lb_prf_add##", $lb_prf_add);
	$tpl->assign("##lb_prf_ine##", $lb_prf_ine);
	$tpl->assign("##lb_prf_prv##", $lb_prf_prv);
	$tpl->assign("##lb_prf_cty##", $lb_prf_cty);
	$tpl->assign("##lb_prf_zip##", $lb_prf_zip);
	$tpl->assign("##lb_prf_tellab##", $lb_prf_tellab);
	$tpl->assign("##lb_prf_tel##", $lb_prf_tel);
	$tpl->assign("##lb_prf_maillab##", $lb_prf_maillab);
	$tpl->assign("##lb_prf_mail##", $lb_prf_mail);
	$tpl->assign("##lb_prf_url##", $lb_prf_url);
	$tpl->assign("##lb_prf_establish##", $lb_prf_establish);
	$tpl->assign("##lb_prf_capital##", $lb_prf_capital);
	$tpl->assign("##lb_prf_parent##", $lb_prf_parent);
	$tpl->assign("##lb_prf_share##", $lb_prf_share);
	$tpl->assign("##lb_prf_employee##", $lb_prf_employee);
	$tpl->assign("##lb_prf_accdate##", $lb_prf_accdate);
	$tpl->assign("##lb_prf_bank##", $lb_prf_bank);
	$tpl->assign("##lb_prf_valcus##", $lb_prf_valcus);
	$tpl->assign("##lb_prf_conlab##", $lb_prf_conlab);
	$tpl->assign("##lb_prf_con##", $lb_prf_con);
	$tpl->assign("##lb_pag_status##", $lb_pag_status);
	$tpl->assign("##lb_status##", $lb_status);
	$tpl->assign("##lb_hom_keytemplate##", $lb_hom_keytemplate);
	$tpl->assign("##lb_hom_keytitlecolor##", $lb_hom_keytitlecolor);
	$tpl->assign("##lb_hom_keytitle##", $lb_hom_keytitle);
	$tpl->assign("##lb_hom_keydetail##", $lb_hom_keydetail);
	$tpl->assign("##lb_hom_keytitle_sub##", $lb_hom_keytitle_sub);
	$tpl->assign("##lb_hom_keydetail_sub##", $lb_hom_keydetail_sub);
	$tpl->assign("##lb_hom_linetitlecolor##", $lb_hom_linetitlecolor);
	$tpl->assign("##lb_hom_linetitle##", $lb_hom_linetitle);
	$tpl->assign("##lb_hom_linedetail##", $lb_hom_linedetail);
	$tpl->assign("##lb_hom_linetitle_sub##", $lb_hom_linetitle_sub);
	$tpl->assign("##lb_hom_linedetail_sub##", $lb_hom_linedetail_sub);
	$tpl->assign("##lb_hom_lineimage##", $lb_hom_lineimage);
	$tpl->assign("##lb_hom_lineimage_width##", $lb_hom_lineimage_width);
	$tpl->assign("##lb_hom_desc##", $lb_hom_desc);
	$tpl->assign("##lb_con_status##", $lb_con_status);
	$tpl->assign("##lb_con_pattern##", $lb_con_pattern);
	$tpl->assign("##lb_con_title##", $lb_con_title);
	$tpl->assign("##lb_con_subtitle##", $lb_con_subtitle);
	$tpl->assign("##lb_con_titlecolor##", $lb_con_titlecolor);
	$tpl->assign("##lb_ban_name##", $lb_ban_name);
	$tpl->assign("##lb_ban_image##", $lb_ban_image);
	$tpl->assign("##lb_ban_link##", $lb_ban_link);
	$tpl->assign("##lb_ban_pospage##", $lb_ban_pospage);
	$tpl->assign("##lb_ban_posside##", $lb_ban_posside);
	$tpl->assign("##lb_bul_name##", $lb_bul_name);
	$tpl->assign("##lb_bul_detail##", $lb_bul_detail);
	$tpl->assign("##lb_bul_image##", $lb_bul_image);
	$tpl->assign("##lb_bul_link##", $lb_bul_link);
	$tpl->assign("##lb_nws_title##", $lb_nws_title);
	$tpl->assign("##lb_nws_sum##", $lb_nws_sum);
	$tpl->assign("##lb_nws_detail##", $lb_nws_detail);
	$tpl->assign("##lb_nws_date##", $lb_nws_date);
	$tpl->assign("##lb_nws_show##", $lb_nws_show);
	$tpl->assign("##lb_nws_status##", $lb_nws_status);
	$tpl->assign("##lb_fea_topimage##", $lb_fea_topimage);
	$tpl->assign("##lb_fea_topimage_width##", $lb_fea_topimage_width);
	$tpl->assign("##lb_fea_topdetail##", $lb_fea_topdetail);
	$tpl->assign("##lb_fea_image_link##", $lb_fea_image_link);
	$tpl->assign("##lb_fea_link##", $lb_fea_link);
	$tpl->assign("##lb_mem_tpm##", $lb_mem_tpm);
	$tpl->assign("##lb_username##", $lb_username);
	$tpl->assign("##lb_password##", $lb_password);
	$tpl->assign("##lb_password_old##", $lb_password_old);
	$tpl->assign("##lb_password_new##", $lb_password_new);
	$tpl->assign("##lb_password_confirm##", $lb_password_confirm);
	$tpl->assign("##lb_comname##", $lb_comname);
	$tpl->assign("##lb_ie##", $lb_ie);
	$tpl->assign("##lb_address##", $lb_address);
	$tpl->assign("##lb_province##", $lb_province);
	$tpl->assign("##lb_country##", $lb_country);
	$tpl->assign("##lb_zip##", $lb_zip);
	$tpl->assign("##lb_comtel##", $lb_comtel);
	$tpl->assign("##lb_comfax##", $lb_comfax);
	$tpl->assign("##lb_commobile##", $lb_commobile);
	$tpl->assign("##lb_commail##", $lb_commail);
	$tpl->assign("##lb_contact##", $lb_contact);
	$tpl->assign("##lb_position##", $lb_position);
	$tpl->assign("##lb_gender##", $lb_gender);
	$tpl->assign("##lb_mail##", $lb_mail);
	$tpl->assign("##lb_oth_mail##", $lb_oth_mail);
	$tpl->assign("##lb_tel##", $lb_tel);
	$tpl->assign("##lb_confirmcode##", $lb_confirmcode);
	$tpl->assign("##lb_confirmcode_text##", $lb_confirmcode_text);
	$tpl->assign("##lb_sort##", $lb_sort);
	$tpl->assign("##lb_sortfix_text##", $lb_sortfix_text);
	$tpl->assign("##lb_male##", $lb_male);
	$tpl->assign("##lb_female##", $lb_female);
	$tpl->assign("##lb_left##", $lb_left);
	$tpl->assign("##lb_right##", $lb_right);
	$tpl->assign("##lb_register##", $lb_register);
	$tpl->assign("##lb_memurl##", $lb_memurl);
	$tpl->assign("##lb_memid##", $lb_memid);
	$tpl->assign("##lb_memtype##", $lb_memtype);
	$tpl->assign("##lb_loginhis##", $lb_loginhis);
	$tpl->assign("##lb_registdate##", $lb_registdate);
	$tpl->assign("##lb_package##", $lb_package);
	$tpl->assign("##lb_start##", $lb_start);
	$tpl->assign("##lb_tempmain##", $lb_tempmain);
	$tpl->assign("##lb_sup_subject##", $lb_sup_subject);
	$tpl->assign("##lb_sup_detail##", $lb_sup_detail);
	$tpl->assign("##lb_subject##", $lb_subject);
	$tpl->assign("##lb_detail##", $lb_detail);
	$tpl->assign("##lb_date##", $lb_date);
	$tpl->assign("##lb_link##", $lb_link);
	$tpl->assign("##lb_contentname##", $lb_contentname);
	$tpl->assign("##lb_memlist##", $lb_memlist);
	$tpl->assign("##lb_width##", $lb_width);
	$tpl->assign("##lb_height##", $lb_height);
	$tpl->assign("##lb_name##", $lb_name);
	$tpl->assign("##lb_memo##", $lb_memo);
	$tpl->assign("##lb_remark##", $lb_remark);
	$tpl->assign("##lb_panelcolor##", $lb_panelcolor);
	$tpl->assign("##lb_nwg_name##", $lb_nwg_name);
	$tpl->assign("##lb_nwe_name##", $lb_nwe_name);
	$tpl->assign("##lb_cate_name##", $lb_cate_name);
	$tpl->assign("##lb_cate_pos##", $lb_cate_pos);
	$tpl->assign("##lb_cate_normal##", $lb_cate_normal);
	$tpl->assign("##lb_cate_main##", $lb_cate_main);
	$tpl->assign("##lb_cate_sub##", $lb_cate_sub);
	$tpl->assign("##lb_cate_under##", $lb_cate_under);
	$tpl->assign("##lb_ie_name##", $lb_ie_name);
	$tpl->assign("##lb_province_name##", $lb_province_name);
	$tpl->assign("##lb_country_name##", $lb_country_name);
	$tpl->assign("##lb_pack_name##", $lb_pack_name);
	$tpl->assign("##lb_tempmain_name##", $lb_tempmain_name);
	$tpl->assign("##lb_tempkey_name##", $lb_tempkey_name);
	$tpl->assign("##lb_clf_code##", $lb_clf_code);
	$tpl->assign("##lb_patterncon_name##", $lb_patterncon_name);
	$tpl->assign("##lb_archive##", $lb_archive);
	$tpl->assign("##lb_title##", $lb_title);
	$tpl->assign("##lb_side##", $lb_side);
	$tpl->assign("##lb_days##", $lb_days);
	$tpl->assign("##lb_months##", $lb_months);
	$tpl->assign("##lb_type##", $lb_type);
	$tpl->assign("##lb_filename##", $lb_filename);
	$tpl->assign("##lb_select##", $lb_select);
	$tpl->assign("##tab_profile##", $tab_profile);
	$tpl->assign("##tab_home##", $tab_home);
	$tpl->assign("##tab_content##", $tab_content);
	$tpl->assign("##tab_presentation##", $tab_presentation);
	$tpl->assign("##tab_inquiry##", $tab_inquiry);
	$tpl->assign("##tab_products##", $tab_products);
	$tpl->assign("##tm_main##", $tm_main);
	$tpl->assign("##tm_top##", $tm_top);
	$tpl->assign("##tm_member##", $tm_member);
	$tpl->assign("##tm_banner##", $tm_banner);
	$tpl->assign("##tm_news##", $tm_news);
	$tpl->assign("##tm_contact##", $tm_contact);
	$tpl->assign("##tm_magazine##", $tm_magazine);
	$tpl->assign("##tm_setting##", $tm_setting);
	$tpl->assign("##tt_category_sort##", $tt_category_sort);
	$tpl->assign("##tt_member_sort##", $tt_member_sort);
	$tpl->assign("##tt_bulletin_sort##", $tt_bulletin_sort);
	$tpl->assign("##tt_banner_sort##", $tt_banner_sort);
	$tpl->assign("##tt_country_sort##", $tt_country_sort);
	$tpl->assign("##tt_home##", $tt_home);
	$tpl->assign("##tt_logout##", $tt_logout);
	$tpl->assign("##tt_memberall##", $tt_memberall);
	$tpl->assign("##tt_memberbsc##", $tt_memberbsc);
	$tpl->assign("##tt_memberfree##", $tt_memberfree);
	$tpl->assign("##tt_member##", $tt_member);
	$tpl->assign("##tt_member_search##", $tt_member_search);
	$tpl->assign("##tt_member_searchcate##", $tt_member_searchcate);
	$tpl->assign("##tt_member_edit##", $tt_member_edit);
	$tpl->assign("##tt_member_info##", $tt_member_info);
	$tpl->assign("##tt_member_page##", $tt_member_page);
	$tpl->assign("##tt_member_template##", $tt_member_template);
	$tpl->assign("##tt_member_contract##", $tt_member_contract);
	$tpl->assign("##tt_member_bulcat##", $tt_member_bulcat);
	$tpl->assign("##tt_member_onoff##", $tt_member_onoff);
	$tpl->assign("##tt_member_inq##", $tt_member_inq);
	$tpl->assign("##tt_feature##", $tt_feature);
	$tpl->assign("##tt_feature_add##", $tt_feature_add);
	$tpl->assign("##tt_feature_edit##", $tt_feature_edit);
	$tpl->assign("##tt_feature_view##", $tt_feature_view);
	$tpl->assign("##tt_update##", $tt_update);
	$tpl->assign("##tt_update_add##", $tt_update_add);
	$tpl->assign("##tt_update_edit##", $tt_update_edit);
	$tpl->assign("##tt_update_delete##", $tt_update_delete);
	$tpl->assign("##tt_introduce##", $tt_introduce);
	$tpl->assign("##tt_introduce_add##", $tt_introduce_add);
	$tpl->assign("##tt_introduce_edit##", $tt_introduce_edit);
	$tpl->assign("##tt_introduce_set##", $tt_introduce_set);
	$tpl->assign("##tt_introduce_set_edit##", $tt_introduce_set_edit);
	$tpl->assign("##tt_news##", $tt_news);
	$tpl->assign("##tt_news_add##", $tt_news_add);
	$tpl->assign("##tt_news_edit##", $tt_news_edit);
	$tpl->assign("##tt_news_delete##", $tt_news_delete);
	$tpl->assign("##tt_newsgenre##", $tt_newsgenre);
	$tpl->assign("##tt_newsgenre_add##", $tt_newsgenre_add);
	$tpl->assign("##tt_newsgenre_edit##", $tt_newsgenre_edit);
	$tpl->assign("##tt_newseditor##", $tt_newseditor);
	$tpl->assign("##tt_newseditor_add##", $tt_newseditor_add);
	$tpl->assign("##tt_newseditor_edit##", $tt_newseditor_edit);
	$tpl->assign("##tt_category##", $tt_category);
	$tpl->assign("##tt_category_add##", $tt_category_add);
	$tpl->assign("##tt_category_edit##", $tt_category_edit);
	$tpl->assign("##tt_ie##", $tt_ie);
	$tpl->assign("##tt_ie_add##", $tt_ie_add);
	$tpl->assign("##tt_ie_edit##", $tt_ie_edit);
	$tpl->assign("##tt_province##", $tt_province);
	$tpl->assign("##tt_province_add##", $tt_province_add);
	$tpl->assign("##tt_province_edit##", $tt_province_edit);
	$tpl->assign("##tt_country##", $tt_country);
	$tpl->assign("##tt_country_add##", $tt_country_add);
	$tpl->assign("##tt_country_edit##", $tt_country_edit);
	$tpl->assign("##tt_package##", $tt_package);
	$tpl->assign("##tt_package_add##", $tt_package_add);
	$tpl->assign("##tt_package_edit##", $tt_package_edit);
	$tpl->assign("##tt_tempmain##", $tt_tempmain);
	$tpl->assign("##tt_tempmain_add##", $tt_tempmain_add);
	$tpl->assign("##tt_tempmain_edit##", $tt_tempmain_edit);
	$tpl->assign("##tt_tempkey##", $tt_tempkey);
	$tpl->assign("##tt_tempkey_add##", $tt_tempkey_add);
	$tpl->assign("##tt_tempkey_edit##", $tt_tempkey_edit);
	$tpl->assign("##tt_fontcolor##", $tt_fontcolor);
	$tpl->assign("##tt_fontcolor_add##", $tt_fontcolor_add);
	$tpl->assign("##tt_fontcolor_edit##", $tt_fontcolor_edit);
	$tpl->assign("##tt_patterncon##", $tt_patterncon);
	$tpl->assign("##tt_patterncon_add##", $tt_patterncon_add);
	$tpl->assign("##tt_patterncon_edit##", $tt_patterncon_edit);
	$tpl->assign("##tt_page##", $tt_page);
	$tpl->assign("##tt_contact##", $tt_contact);
	$tpl->assign("##tt_contact_view##", $tt_contact_view);
	$tpl->assign("##tt_magazine##", $tt_magazine);
	$tpl->assign("##tt_magazine_add##", $tt_magazine_add);
	$tpl->assign("##tt_magazine_edit##", $tt_magazine_edit);
	$tpl->assign("##tt_magazine_view##", $tt_magazine_view);
	$tpl->assign("##tt_bannerspccate##", $tt_bannerspccate);
	$tpl->assign("##tt_bannerspc##", $tt_bannerspc);
	$tpl->assign("##tt_bannerbsc##", $tt_bannerbsc);
	$tpl->assign("##tt_bannerbsc2##", $tt_bannerbsc2);
	$tpl->assign("##tt_banner##", $tt_banner);
	$tpl->assign("##tt_banner_add##", $tt_banner_add);
	$tpl->assign("##tt_banner_edit##", $tt_banner_edit);
	$tpl->assign("##tt_bulletin##", $tt_bulletin);
	$tpl->assign("##tt_bulletin_add##", $tt_bulletin_add);
	$tpl->assign("##tt_bulletin_edit##", $tt_bulletin_edit);
	$tpl->assign("##tt_bulletin_delete##", $tt_bulletin_delete);
	$tpl->assign("##tt_bannercate##", $tt_bannercate);
	$tpl->assign("##tt_bannercate_add##", $tt_bannercate_add);
	$tpl->assign("##tt_bannercate_edit##", $tt_bannercate_edit);
	$tpl->assign("##tt_bulletincate##", $tt_bulletincate);
	$tpl->assign("##tt_bulletincate_add##", $tt_bulletincate_add);
	$tpl->assign("##tt_bulletincate_edit##", $tt_bulletincate_edit);
	$tpl->assign("##tt_expirewarning##", $tt_expirewarning);
	$tpl->assign("##tt_datalock##", $tt_datalock);
	$tpl->assign("##tx_confirmdelete##", $tx_confirmdelete);
	$tpl->assign("##tt_product_add##", $tt_product_add);
	$tpl->assign("##lb_product_topimage_width##", $lb_product_topimage_width);

	$tpl->assign("##lb_product_topimage##", $lb_product_topimage);
	$tpl->assign("##lb_product_thumb_01##", $lb_product_thumb_01);
	$tpl->assign("##lb_product_thumb_02##", $lb_product_thumb_02);
	$tpl->assign("##lb_product_thumb_03##", $lb_product_thumb_03);
	$tpl->assign("##lb_product_thumb_04##", $lb_product_thumb_04);
	$tpl->assign("##lb_product_specification##", $lb_product_specification);
	$tpl->assign("##lb_product_topdetail##", $lb_product_topdetail);
	$tpl->assign("##lb_product_supplier##", $lb_product_supplier);
	$tpl->assign("##tt_products_manager##", $tt_products_manager);
	$tpl->assign("##tt_products_categorys_manager##", $tt_products_categorys_manager);
	$tpl->assign("##tt_product_category##", $tt_product_category);
	$tpl->assign("##tt_product_edit##", $tt_product_edit);
	$tpl->assign("##tt_product_category_add##", $tt_product_category_add);
	$tpl->assign("##lb_pro_cat_des##", $lb_pro_cat_des);
	$tpl->assign("##lb_fea_category##", $lb_fea_category);
	$tpl->assign("##tt_fea_products_manager##", $tt_fea_products_manager);
	$tpl->assign("##tm_product##", $tm_product);
	$tpl->assign("##tt_mail_products_manager##", $tt_mail_products_manager);
	$tpl->assign("##tt_member_product_search##", $tt_member_product_search);
	$tpl->assign("##lb_prf_product_name##", $lb_prf_product_name);
	$tpl->assign("##lb_prf_product_sku##", $lb_prf_product_sku);
	$tpl->assign("##tt_product_category_edit##", $tt_product_category_edit);
	$tpl->assign("##tm_events##", $tm_events);
	$tpl->assign("##tt_event_add##", $tt_event_add);
	$tpl->assign("##lb_event_title##", $lb_event_title);
	$tpl->assign("##lb_event_detail##", $lb_event_detail);
	$tpl->assign("##lb_event_status##", $lb_event_status);
	$tpl->assign("##tt_oncoming_events##", $tt_oncoming_events);
	$tpl->assign("##tt_events##", $tt_events);

	$tpl->assign("##mn_mailin##", $mn_mailin);
	$tpl->assign("##lb_mail_subject##", $lb_mail_subject);
	$tpl->assign("##lb_mail_content##", $lb_mail_content);
	$tpl->assign("##lb_mail_company##", $lb_mail_company);
	$tpl->assign("##lb_mail_contactname##", $lb_mail_contactname);
	$tpl->assign("##lb_mail_tel##", $lb_mail_tel);
	$tpl->assign("##lb_mail_fax##", $lb_mail_fax);
	$tpl->assign("##lb_mail_email##", $lb_mail_email);

	//Count mail magazine
	$sqljp = "select * from flc_member where mem_status = '' and mem_mailop_mag = '1' AND mem_national =  'jp';"; 
	$sqljp2 = "select * from flc_member where mem_status = '' and mem_mailop_mag = '1' AND mem_national =  'jp' AND mem_oth_contactmail<>'' ;"; 

	$queryjp=mysql_query($sqljp);

	while ($result_jp = mysql_fetch_array($queryjp)) {

		$summail_jp[]= (explode(",",$result_jp['mem_contactmail']));

		if ($result_jp['mem_oth_contactmail']!='') {

			$summail_oth_jp[]= $result_jp['mem_oth_contactmail'];
		}
	}

	$sqlvn = "select * from flc_member where mem_status = '' and mem_mailop_mag = '1' AND mem_national =  'vn' AND mem_contactmail<>'' ;";
	$queryvn=mysql_query($sqlvn); 
	$sqloth= "select * from flc_member where mem_status = '' and mem_mailop_mag = '1' AND mem_national <> 'jp' AND mem_national <>  'vn' AND mem_contactmail<>'' ;";

	$queryoth=mysql_query( $sqloth); 
	$tpl->assign("##summailjp##", count($summail_jp));
	$tpl->assign("##summailvn##", mysql_num_rows($queryvn));
	$tpl->assign("##summailoth##", mysql_num_rows($queryoth));

	//..........Start Count member..........

	$sql11 = "select * from flc_member where mem_national =  'jp';";   
	$query11=mysql_query($sql11);
	while ($result_11 = mysql_fetch_array($query11)) {
		$summam_jp[]= (explode(",",$result_11['mem_national']));
	}

	$sqlvn12 = "select * from flc_member where mem_national =  'vn';";
	$queryvn12=mysql_query($sqlvn12); 
	$sqloth13= "select * from flc_member where mem_national =  'oo';";
	$queryoth13=mysql_query( $sqloth13);

	$tpl->assign("##memjp11##", count($summam_jp));
	$tpl->assign("##memvn12##", mysql_num_rows($queryvn12));
	$tpl->assign("##memoth13##", mysql_num_rows($queryoth13));
	
	//................End Count member.............
?>