<?php
	
	// language
	if ($_COOKIE['vlang'] == 'en') { 
		
		$langpicjp = "lang_jp_01.png"; $langpicvn = "lang_vn_01.png"; $langpicen = "lang_en_02.png";
		$headlogo = "header_07_en.png";
		$texttitlebar = "FACT-LINK : : Japan - Vietnam Industrial Directory";
		
		$tb_pagename = "PAGE NAME";
		$tb_option = "OPTION";
		$tb_lang = "LANGUAGE";
		$tb_status = "STATUS";
		$tb_edit = "EDIT";
		$tb_subject = "SUBJECT";
		$tb_date = "DATE";
		
		$lb_nationality = "Company Nationality";
		$lb_njp = "Japanese";
		$lb_nvn = "Vietnamese";
		$lb_nother = "Other Nation";
		
		$lb_en = "EN";
		$lb_jp = "JP";
		$lb_vn = "VN";
		$lb_en_full = "English Page";
		$lb_jp_full = "Japanese Page";
		$lb_vn_full = "Vietnam Page";
		$lb_back = "Back";
		$lb_enable = "Enable";
		$lb_status = "Disable";
		$lb_left = "Left";
		$lb_right = "Right";
		$lb_pag_name = "Menu Name";
		$lb_pag_pagetitle = "Title Bar Name";
		$lb_pag_sort = "Order No.";
		$lb_pag_textcolor = "Title Color";
		$lb_pag_title = "Title";
		$lb_pag_detail = "Detail";
		$lb_pag_image = "Image";
		$lb_pag_image_width = "Image Width (px)";
		$lb_pag_image_link = "Link to original size";
		$lb_pag_image_disable = "Disable image";
		$lb_pag_video_link = "Video link";
		$lb_pag_media_option = "Media option";
		$lb_pag_media_remove = "Remove media";
		$lb_mem_subdesc = "Company Slogan";
		$lb_mem_category = "Category";
		$lb_mem_maincategory = "Main Category";
		$lb_mem_subcategory = "Sub Category";
		$lb_mem_footer = "Footer";
		$lb_prf_comname = "Company Name";
		$lb_prf_comname_aka = "Similar Company Name";
		$lb_prf_pername = "Representative Name";
		$lb_prf_posname = "Position";
		$lb_prf_business = "Business Description";
		$lb_prf_product = "Produce";
		$lb_prf_seocom = "Company Description (SEO)";
		$lb_prf_seokey = "Keyword (SEO)";
		$lb_prf_addlab = "Address Label";
		$lb_prf_add = "Address";
		$lb_prf_ine = "Industrial Estate";
		$lb_prf_prv = "Province";
		$lb_prf_cty = "Country";
		$lb_prf_zip = "Portal Code";
		$lb_prf_tellab = "Tel / Fax Label";
		$lb_prf_tel = "Tel / Fax";
		$lb_prf_maillab = "E-mail Label";
		$lb_prf_mail = "E-mail";
		$lb_prf_url = "Website";
		$lb_prf_establish = "Establish Date";
		$lb_prf_capital = "Capital";
		$lb_prf_parent = "Parent Company";
		$lb_prf_share = "Shareholder";
		$lb_prf_employee = "Employee";
		$lb_prf_accdate = "Account Period";
		$lb_prf_bank = "Bank";
		$lb_prf_valcus = "Value Customer";
		$lb_prf_conlab = "Content Label";
		$lb_prf_con = "Content Detail";
		$lb_prf_textcolor = "Label Color";
		
		$lb_hom_keytemplate = "Key Panel Style";
		$lb_hom_keytitlecolor = "3 Key Panel Title Color";
		$lb_hom_keytitle = "3 Key Panel Title";
		$lb_hom_keydetail = "3 Key Panel Detail";
		$lb_hom_keytitle_sub = "Key Panel Title";
		$lb_hom_keydetail_sub = "Key Panel Detail";
		$lb_hom_linetitlecolor = "3 Appeal Title Color";
		$lb_hom_linetitle = "3 Appeal Title";
		$lb_hom_linedetail = "3 Appeal Detail";
		$lb_hom_linetitle_sub = "Appeal Title";
		$lb_hom_linedetail_sub = "Appeal Detail";
		$lb_hom_lineimage = "Appeal Image";
		$lb_hom_lineimage_width = "Appeal Image Width (px)";
		$lb_hom_desc = "Bottom Note";
		
		$lb_con_status = "Column Status";
		$lb_con_pattern = "Column Pattern";
		$lb_con_title = "Column Title";
		$lb_con_subtitle = "Column Subtitle";
		$lb_con_titlecolor = "Column Title Color";
		
		$lb_pst_template = "Presentation Template";
		$lb_pst_title = "Presentation Title";
		$lb_pst_title_detail = "Presentation Detail";
		$lb_pst_bottom = "Bottom Note Title";
		$lb_pst_bottom_detail = "Bottom Note Detail";
		$lb_box = "Presentation Box";
		$lb_text = "Text Type";
		$lb_image = "Image Type";
		
		$lb_mail_to = "Name of Receiver";
		$lb_mail_mail = "Destination E-mail";
		$lb_mail_subject = "Subject";
		$lb_mail_detail = "Detail";
		$lb_mail_by = "By";
		$lb_mail_company = "Company";
		$lb_mail_department = "Department";
		$lb_mail_contactname = "Your Name";
		$lb_mail_tel = "TEL";
		$lb_mail_fax = "FAX";
		$lb_mail_email = "E-mail";
		$lb_mail_content = "Content";
		
		$lb_mem_contactinfo = "Contact Information";
		$lb_mem_id = "MEMBER ID";
		$lb_mem_url = "MEMBER URL";
		$lb_mem_registered = "REGISTERED DATE";
		$lb_mem_current = "CURRENT CONTRACT";
		$lb_mem_package = "PACKAGE";
		
		$lb_username = "Username";
		$lb_password = "Password";
		$lb_password_old = "Current Password";
		$lb_password_new = "New Password";
		$lb_password_confirm = "Re-enter New Password";
		$lb_comname = "Company Name";
		$lb_ie = "Industrial Estate";
		$lb_address = "Address";
		$lb_province = "Province";
		$lb_country = "Country";
		$lb_zip = "Portal Code";
		$lb_comtel = "Tel.";
		$lb_comfax = "Fax";
		$lb_contact = "Contact Name";
		$lb_position = "Contact Position";
		$lb_gender = "Gender";
		$lb_mail = "Contact E-mail";
		$lb_tel = "Contact Tel.";
		$lb_confirmcode = "Confirm Code";
		$lb_confirmcode_text = "Please fill 4 digits in this box to confirm this form.";
		$lb_male = "Male";
		$lb_female = "Female";
		$lb_register = "Register";
		$lb_memurl = "URL";
		$lb_memid = "Member ID";
		$lb_memtype = "Member Type";
		$lb_loginhis = "Login History";
		$lb_tempmain = "Main Template";
		$lb_maxwidth = "Maximum width";
		$lb_filetype = "File type";
		$lb_sup_subject = "Subject";
		$lb_sup_detail = "Detail";
		
		$lb_title_editor = "Member Editor";
		$lb_title_admin = "Admin Editor";
		
		$lb_alt_on = "ON (Click to set OFF)";
		$lb_alt_off = "OFF (Click to set ON)";
		$lb_alt_edit = "Edit";
		$lb_alt_expand = "Add Detail";
		$lb_alt_view = "View";
		$lb_alt_create = "Create New Page";
		$lb_alt_delete = "Delete";
		
		$lb_select = "----- Please Select -----";
		
		$tab_profile = "COMPANY PROFILE";
		$tab_home = "HOME";
		$tab_content = "CONTENT";
		$tab_presentation = "PRESENTATION";
		$tab_inquiry = "INQUIRY";
		$tab_products = "PRODUCTS";
		
		$mn_info = "User Information";
		$mn_edit = "Edit Profile";
		$mn_pass = "Change Password";
		$mn_logout = "Logout";
		$mn_page = "Page Management";
		$mn_template = "Change Template";
		$mn_mailin = "Mail - Inbox";
		$mn_mailout = "Mail - Outbox";
		$mn_mailnew = "Mail - Compose";
		$mn_maildel = "Mail - Delete";
		$mn_support = "Support Form";
		$mn_main = "Main";
		$mn_mail = "Mailbox";
		$mn_help = "Support";
		
		$mm_prf_add = "Add Company Profile";
		$mm_hom_add = "Add Home";
		$mm_inq_add = "Add Inquiry";
		$mm_pst_add = "Add Presentation";
		$mm_box_add = "Add Presentation Box";
		$mm_con_add = "Add Content";
		$mm_col_add = "Add Column";
		$mm_prf_edit = "Edit Company Profile";
		$mm_hom_edit = "Edit Home";
		$mm_inq_edit = "Edit Inquiry";
		$mm_pst_edit = "Edit Presentation";
		$mm_box_edit = "Edit Presentation Box";
		$mm_con_edit = "Edit Content";
		$mm_col_edit = "Edit Column";
		$mm_col_delete = "Delete Column";
		$mm_box_delete = "Delete Presentation Box";
		
		$me_en = "EN";
		$me_jp = "JP";
		$me_vn = "VN";
		$me_edit = "Edit";
		$me_enable = "ENABLE";
		$me_disable = "DISABLE";
		$me_page = "Page";
		
		$bn_edit = "EDIT";
		
		$tx_supportsent = "Your inquiry has been sent.";
		$tx_confirmdelete = "Are you sure to delete this?";
		
		$tm_main = "Main";
		$tm_top = "Top Page";
		$tm_banner = "Banner";
		$tm_member = "Member";
		$tm_news = "News";
		$tm_contact = "Contact";
		$tm_magazine = "Magazine";
		$tm_setting = "Setting";
		
		$tt_home = "Home";
		$tt_logout = "Logout";
		$tt_memberall = "All Member List";
		$tt_memberbsc = "Basic Member List";
		$tt_memberfree = "Free Member List";
		$tt_member = "Member List";
		$tt_member_search = "Search Member";
		$tt_member_searchcate = "Search Member by Category";
		$tt_member_edit = "Edit Member";
		$tt_member_info = "Member Information";
		$tt_member_page = "Page Management";
		$tt_member_template = "Change Template";
		$tt_member_contract = "Edit Contract";
		$tt_member_bulcat = "Category Bulletin";
		$tt_member_onoff = "Change Status";
		$tt_member_inq = "Inquiry List";
		$tt_feature = "Feature Article List";
		$tt_feature_add = "Add Feature Article";
		$tt_feature_edit = "Edit Feature Article";
		$tt_feature_view = "View Feature Article";
		$tt_update = "Updated Info List";
		$tt_update_add = "Add Updated Info";
		$tt_update_edit = "Edit Updated Info";
		$tt_update_delete = "Delete Updated Info";
		$tt_introduce = "Introduce Company List";
		$tt_introduce_add = "Add Introduce Company";
		$tt_introduce_edit = "Edit Introduce Company";
		$tt_introduce_set = "Introduce Company Set List";
		$tt_introduce_set_edit = "Edit Introduce Company Set";
		$tt_news = "News List";
		$tt_news_add = "Add News";
		$tt_news_edit = "Edit News";
		$tt_news_delete = "Delete News";
		$tt_newsgenre = "News Gerne List";
		$tt_newsgenre_add = "Add News Gerne";
		$tt_newsgenre_edit = "Edit News Gerne";
		$tt_newseditor = "News Editor List";
		$tt_newseditor_add = "Add News Editor";
		$tt_newseditor_edit = "Edit News Editor";
		$tt_category = "Category List";
		$tt_category_add = "Add Category";
		$tt_category_edit = "Edit Category";
		$tt_ie = "Industrial Estate List";
		$tt_ie_add = "Add Industrial Estate";
		$tt_ie_edit = "Edit Industrial Estate";
		$tt_province = "Province List";
		$tt_province_add = "Add Province";
		$tt_province_edit = "Edit Province";
		$tt_country = "Country List";
		$tt_country_add = "Add Country";
		$tt_country_edit = "Edit Country";
		$tt_package = "Package List";
		$tt_package_add = "Add Package";
		$tt_package_edit = "Edit Package";
		$tt_tempmain = "Main Template List";
		$tt_tempmain_add = "Add Main Template";
		$tt_tempmain_edit = "Edit Main Template";
		$tt_tempkey = "Key Template List";
		$tt_tempkey_add = "Add Key Template";
		$tt_tempkey_edit = "Edit Key Template";
		$tt_fontcolor = "Font Color List";
		$tt_fontcolor_add = "Add Font Color";
		$tt_fontcolor_edit = "Edit Font Color";
		$tt_patterncon = "Content Pattern List";
		$tt_patterncon_add = "Add Content Pattern";
		$tt_patterncon_edit = "Edit Content Pattern";
		$tt_page = "Page Management";
		$tt_contact = "Contact List";
		$tt_contact_view = "View Contact";
		$tt_magazine = "Mail Magazine List";
		$tt_magazine_add = "Add Mail Magazine";
		$tt_magazine_edit = "Edit Mail Magazine";
		$tt_magazine_view = "View Mail Magazine";
		$tt_bannerspccate = "Special Banner by Category";
		$tt_bannerspc = "Special Banner List";
		$tt_bannerbsc = "Basic Banner List";
		$tt_bannerbsc2 = "Basic Banner by Category";
		$tt_banner = "Banner List";
		$tt_banner_add = "Add Banner";
		$tt_banner_edit = "Edit Banner";
		$tt_bulletin = "Bulletin List";
		$tt_bulletin_add = "Add Bulletin";
		$tt_bulletin_edit = "Edit Bulletin";
		$tt_bulletin_delete = "Delete Bulletin";
		$tt_bannercate = "Category Banner List";
		$tt_bannercate_add = "Add Category Banner";
		$tt_bannercate_edit = "Edit Category Banner";
		$tt_bulletincate = "Category Bulletin List";
		$tt_bulletincate_add = "Add Category Bulletin";
		$tt_bulletincate_edit = "Edit Category Bulletin";
		$tt_expirewarning = "Expire Warning";
		$tt_lock = "Data Locked";

		$tm_product = "Products";
		$tt_products_manager = "Products Manager";
		$tt_products_categorys_manager = "Products Category Manager";
		$tt_fea_products_manager = "Featured Products";
		$tt_mail_products_manager = "Mail Product List";
		$product_name = "Product Name";
		$access_report = "Access Report";
		$mapCode = "Map Code";
		
	} 
	
	else if ($_COOKIE['vlang'] == 'vn') { 
		
		$langpicjp = "lang_jp_01.png"; $langpicvn = "lang_vn_02.png"; $langpicen = "lang_en_01.png";
		$headlogo = "header_07_vn.png";
		$texttitlebar = "FACT-LINK : : Cổng thông tin dành cho các doanh nghiệp Nhật Bản và Việt Nam";
		
		$tb_pagename = "Tên trang";
		$tb_option = "Tùy chọn";
		$tb_lang = "Ngôn ngữ";
		$tb_status = "Tình trạng";
		$tb_edit = "Chỉnh sửa";
		$tb_subject = "Tiêu đề";
		$tb_date = "Ngày tháng";
		
		$lb_nationality = "Company Nationality";
		$lb_njp = "Japanese";
		$lb_nvn = "Vietnamese";
		$lb_nother = "Other Nation";
		
		$lb_en = "EN";
		$lb_jp = "JP";
		$lb_vn = "VN";
		$lb_en_full = "Trang tiếng Anh";
		$lb_jp_full = "Trang tiếng Nhật";
		$lb_vn_full = "Trang tiếng Việt";
		$lb_back = "Quay lại";
		$lb_enable = "Bật";
		$lb_status = "Tắt";
		$lb_left = "Trái";
		$lb_right = "Phải";
		$lb_pag_name = "Tên menu";
		$lb_pag_pagetitle = "Tên thanh tiêu đề";
		$lb_pag_sort = "Thứ tự";
		$lb_pag_textcolor = "Màu tiêu đề";
		$lb_pag_title = "Tiêu đề";
		$lb_pag_detail = "Chi tiết";
		$lb_pag_image = "Hình ảnh";
		$lb_pag_image_width = "Bề ngang hình ảnh (px)";
		$lb_pag_image_link = "Liên kết tới kích thước gốc";
		$lb_pag_image_disable = "Tắt hình ảnh";
		$lb_pag_video_link = "Liên kết hình ảnh";
		$lb_pag_media_option = "Loại đa phương tiện";
		$lb_pag_media_remove = "Gỡ bỏ đa phương tiện";
		$lb_mem_subdesc = "Slogan công ty";
		$lb_mem_category = "Mục";
		$lb_mem_maincategory = "Mục 1";
		$lb_mem_subcategory = "Mục 2";
		$lb_mem_footer = "Chân trang";
		$lb_prf_comname = "Tên công ty";
		$lb_prf_comname_aka = "Tên công ty tương tự";
		$lb_prf_pername = "Tên người đại diện";
		$lb_prf_posname = "Vị trí";
		$lb_prf_business = "Mô tả kinh doanh";
		$lb_prf_product = "Sản phẩm";
		$lb_prf_seocom = "Mô tả công ty";
		$lb_prf_seokey = "Từ khóa";
		$lb_prf_addlab = "Địa chỉ	 nhãn";
		$lb_prf_add = "Địa chỉ";
		$lb_prf_ine = "Khu công nghiệp";
		$lb_prf_prv = "Tỉnh thành";
		$lb_prf_cty = "Quốc gia";
		$lb_prf_zip = "Mã bưu chính";
		$lb_prf_tellab = "Số điện thoại/ Số fax";
		$lb_prf_tel = "Số điện thoại";
		$lb_prf_maillab = "Nhãn mail";
		$lb_prf_mail = "Địa chỉ mail";
		$lb_prf_url = "Địa chỉ trang web";
		$lb_prf_establish = "Ngày thành lập";
		$lb_prf_capital = "Vốn";
		$lb_prf_parent = "Công ty mẹ";
		$lb_prf_share = "Cổ đông chính";
		$lb_prf_employee = "Nhân viên";
		$lb_prf_accdate = "Kỳ quyết toán năm";
		$lb_prf_bank = "Ngân hàng giao dịch chính";
		$lb_prf_valcus = "Khách hàng lớn";
		$lb_prf_conlab = "Nội dung";
		$lb_prf_con = "Chi tiết nội dung";
		$lb_prf_textcolor = "Màu sắc";
		
		$lb_hom_keytemplate = "Kiểu key panel";
		$lb_hom_keytitlecolor = "Màu sắc tiêu đề 3 key panel";
		$lb_hom_keytitle = "Tiêu đề 3 key panel";
		$lb_hom_keydetail = "Chi tiết 3 key panel";
		$lb_hom_keytitle_sub = "Tiêu đề key panel";
		$lb_hom_keydetail_sub = "Chi tiết key panel";
		$lb_hom_linetitlecolor = "Màu sắc tiêu đề 3 yêu cầu";
		$lb_hom_linetitle = "Tiêu đề 3 yêu cầu";
		$lb_hom_linedetail = "Chi tiết 3 yêu cầu";
		$lb_hom_linetitle_sub = "Tiêu đề yêu cầu";
		$lb_hom_linedetail_sub = "Chi tiết yêu cầu";
		$lb_hom_lineimage = "Hình ảnh yêu cầu";
		$lb_hom_lineimage_width = "Bề ngang hình ảnh (px)";
		$lb_hom_desc = "Ghi chú phần cuối";
		
		$lb_con_status = "Cột trạng thái";
		$lb_con_pattern = "Cột mẫu";
		$lb_con_title = "Tiêu đề cột";
		$lb_con_subtitle = "Tiêu đề phụ của cột";
		$lb_con_titlecolor = "Màu sắc của cột";
		
		$lb_pst_template = "Giao diện Presentation";
		$lb_pst_title = "Tiêu đề Presentation";
		$lb_pst_title_detail = "Chi tiết Presentation";
		$lb_pst_bottom = "Tiêu đề ghi chú ở phần cuối";
		$lb_pst_bottom_detail = "Chi tiết ghi chú ở phần cuối";
		$lb_box = "Thư mục Presentation";
		$lb_text = "Kiểu chữ";
		$lb_image = "Kiểu hình ảnh";
		
		$lb_mail_to = "Tên người nhận";
		$lb_mail_mail = "Nơi đến của email";
		$lb_mail_subject = "Tiêu đề";
		$lb_mail_detail = "Chi tiết";
		$lb_mail_by = "Theo";
		$lb_mail_company = "Công ty";
		$lb_mail_department = "Lĩnh vực";
		$lb_mail_contactname = "Tên của bạn";
		$lb_mail_tel = "Số điện thoại";
		$lb_mail_fax = "Số fax";
		$lb_mail_email = "Địa chỉ mail";
		$lb_mail_content = "Nội dung";
		
		$lb_mem_contactinfo = "Thông tin liên hệ";
		$lb_mem_id = "ID của thành viên";
		$lb_mem_url = "Đường dẫn của thành viên";
		$lb_mem_registered = "Ngày đăng ký";
		$lb_mem_current = "Hợp đồng hiện tại";
		$lb_mem_package = "Gói";
		
		$lb_username = "Tên người dùng";
		$lb_password = "Mật khẩu";
		$lb_password_old = "Mật khẩu hiện tại";
		$lb_password_new = "Mật khẩu mới";
		$lb_password_confirm = "Nhập lại mật khẩu mới";
		$lb_comname = "Tên công ty";
		$lb_ie = "Khu công nghiệp";
		$lb_address = "Địa chỉ";
		$lb_province = "Tỉnh thành";
		$lb_country = "Quốc gia";
		$lb_zip = "Mã bưu chính";
		$lb_comtel = "Số điện thoại";
		$lb_comfax = "Số fax";
		$lb_contact = "Tên liêc hệ";
		$lb_position = "Vị trí liên hệ";
		$lb_gender = "Giới tính";
		$lb_mail = "Địa chỉ mail liên lạc";
		$lb_tel = "Số điện thoại liên lạc";
		$lb_confirmcode = "Mã xác nhận";
		$lb_confirmcode_text = "Xin vui lòng điền vào 4 chữ số trong ô này để xác nhận.";
		$lb_male = "Nam";
		$lb_female = "Nữ";
		$lb_register = "Đăng ký";
		$lb_memurl = "Đường dẫn";
		$lb_memid = "ID của thành viên";
		$lb_memtype = "Kiểu thành viên";
		$lb_loginhis = "Lịch sử đăng nhập";
		$lb_tempmain = "Giao diện chính";
		$lb_maxwidth = "Bề ngang lớn nhất";
		$lb_filetype = "Kiểu tệp tin";
		$lb_sup_subject = "Tiêu đề";
		$lb_sup_detail = "Chi tiết";
		
		$lb_title_editor = "Bộ soạn thảo của thành viên";
		$lb_title_admin = "Bộ soạn thảo của admin";
		
		$lb_alt_on = "MỞ (Nhấp vào để TẮT)";
		$lb_alt_off = "TẮT (Nhấp vào để MỞ)";
		$lb_alt_edit = "Chỉnh sửa";
		$lb_alt_expand = "Thêm chi tiết";
		$lb_alt_view = "Xem";
		$lb_alt_create = "Tạo trang mới";
		$lb_alt_delete = "Xóa";
		
		$lb_select = "----- Vui long lựa chọn -----";
		
		$tab_profile = "Hồ sơ công ty";
		$tab_home = "Trang chủ";
		$tab_content = "Nội dung";
		$tab_presentation = "Presentation";
		$tab_inquiry = "Yêu cầu";
		$tab_products = "Sản phẩm";
		
		$mn_info = "Thông tin người dùng";
		$mn_edit = "Chỉnh sửa hồ sơ";
		$mn_pass = "Thay đổi mật khẩu";
		$mn_logout = "Đăng xuất";
		$mn_page = "Quản lý trang";
		$mn_template = "Giao diện";
		$mn_mailin = "Hộp thư đến";
		$mn_mailout = "Hộp thư đi";
		$mn_mailnew = "Soạn thư";
		$mn_maildel = "Xóa";
		$mn_support = "Hỗ trợ";
		$mn_main = "Trang chính";
		$mn_mail = "Hộp thư";
		$mn_help = "Hỗ trợ";
		
		$mm_prf_add = "Thêm hồ sơ công ty";
		$mm_hom_add = "Thêm trang chủ";
		$mm_inq_add = "Thêm yêu cầu";
		$mm_pst_add = "Thêm Presentation";
		$mm_box_add = "Thêm Presentation Box";
		$mm_con_add = "Thêm nội dung";
		$mm_col_add = "Thêm cột";
		$mm_prf_edit = "Chỉnh sửa hồ sơ công ty";
		$mm_hom_edit = "Chỉnh sửa trang chủ";
		$mm_inq_edit = "Chỉnh sửa yêu cầu";
		$mm_pst_edit = "Chỉnh sửa Presentation";
		$mm_box_edit = "Chỉnh sửa Presentation Box";
		$mm_con_edit = "Chỉnh sửa nội dung";
		$mm_col_edit = "Chỉnh sửa cột";
		$mm_col_delete = "Xóa cột";
		$mm_box_delete = "Xóa Presentation Box";
		
		$me_en = "EN";
		$me_jp = "JP";
		$me_vn = "VN";
		$me_edit = "Chỉnh sửa";
		$me_enable = "Bật";
		$me_disable = "Tắt";
		$me_page = "Trang";
		
		$bn_edit = "Chỉnh sửa";
		
		$tx_supportsent = "Yêu cầu của bạn đã được gửi đi.";
		$tx_confirmdelete = "Bạn có chắc muốn xóa?";
		
		$tm_main = "Trang chính";
		$tm_top = "Đầu trang";
		$tm_banner = "Banner";
		$tm_member = "Thành viên";
		$tm_news = "Tin tức";
		$tm_contact = "Liên hệ";
		$tm_magazine = "Tạp chí";
		$tm_setting = "Thiết lập";
		
		$tt_home = "Trang chủ";
		$tt_logout = "Đăng xuất";
		$tt_memberall = "Tất cả danh sách thành viên";
		$tt_memberbsc = "Danh sách thành viên cơ bản";
		$tt_memberfree = "Danh sách thành viên miễn phí";
		$tt_member = "Danh sách thành viên";
		$tt_member_search = "Tìm kiếm thành viên";
		$tt_member_searchcate = "Tìm kiếm thành viên theo danh mục";
		$tt_member_edit = "Chỉnh sửa thành viên";
		$tt_member_info = "Thông tin thành viên";
		$tt_member_page = "Quản lý trang";
		$tt_member_template = "Giao diện";
		$tt_member_contract = "Chỉnh sửa hợp đồng";
		$tt_member_bulcat = "Mục bản tin";
		$tt_member_onoff = "Thay đổi trạng thái";
		$tt_member_inq = "Danh sách yêu cầu";
		$tt_feature = "Danh sách bài viết nổi bật";
		$tt_feature_add = "Thêm bài viết nổi bật";
		$tt_feature_edit = "Chỉnh sửa bài viết nổi bật";
		$tt_feature_view = "Xem bài viết nổi bật";
		$tt_update = "Danh sách thông tin được cập nhật";
		$tt_update_add = "Thêm thông tin được cập nhật";
		$tt_update_edit = "Chỉnh sửa thông tin được cập nhật";
		$tt_update_delete = "Xóa thông tin được cập nhật";
		$tt_introduce = "Giới thiệu công ty";
		$tt_introduce_add = "Thêm giới thiệu công ty";
		$tt_introduce_edit = "Chỉnh sửa giới thiệu công ty";
		$tt_introduce_set = "Danh sách tập hợp giới thiệu công ty";
		$tt_introduce_set_edit = "Chỉnh sửa tập hợp giới thiệu công ty";
		$tt_news = "Thêm danh sách";
		$tt_news_add = "Thêm tin tức";
		$tt_news_edit = "Chỉnh sửa tin tức";
		$tt_news_delete = "Xóa tin tức";
		$tt_newsgenre = "Danh sách loại tin tức";
		$tt_newsgenre_add = "Thêm loại tin tức";
		$tt_newsgenre_edit = "Chỉnh sửa loại tin tức";
		$tt_newseditor = "Danh sách người biên tập";
		$tt_newseditor_add = "Thêm người biên tập";
		$tt_newseditor_edit = "Chỉnh sửa người biên tập";
		$tt_category = "Danh sách các danh mục";
		$tt_category_add = "Thêm danh mục";
		$tt_category_edit = "Chỉnh sửa danh mục";
		$tt_ie = "Danh sách khu công nghiệp";
		$tt_ie_add = "Thêm khu công nghiệp";
		$tt_ie_edit = "Chỉnh sửa khu công nghiệp";
		$tt_province = "Danh sách tỉnh thành";
		$tt_province_add = "Thêm tỉnh thành";
		$tt_province_edit = "Chỉnh sửa tỉnh thành";
		$tt_country = "Danh sách quốc gia";
		$tt_country_add = "Thêm quốc gia";
		$tt_country_edit = "Chỉnh sửa quốc gia";
		$tt_package = "Danh sách gói";
		$tt_package_add = "Thêm gói";
		$tt_package_edit = "Chỉnh sửa gói";
		$tt_tempmain = "Main Template List";
		$tt_tempmain_add = "Add Main Template";
		$tt_tempmain_edit = "Edit Main Template";
		$tt_tempkey = "Key Template List";
		$tt_tempkey_add = "Add Key Template";
		$tt_tempkey_edit = "Edit Key Template";
		$tt_fontcolor = "Font Color List";
		$tt_fontcolor_add = "Add Font Color";
		$tt_fontcolor_edit = "Edit Font Color";
		$tt_patterncon = "Content Pattern List";
		$tt_patterncon_add = "Add Content Pattern";
		$tt_patterncon_edit = "Edit Content Pattern";
		$tt_page = "Quản lý trang";
		$tt_contact = "Danh sách liên lạc";
		$tt_contact_view = "Xem liên lạc";
		$tt_magazine = "Mail Magazine List";
		$tt_magazine_add = "Add Mail Magazine";
		$tt_magazine_edit = "Edit Mail Magazine";
		$tt_magazine_view = "View Mail Magazine";
		$tt_bannerspccate = "Banner đặc biệt theo mục";
		$tt_bannerspc = "Danh sách banner đặc biệt";
		$tt_bannerbsc = "Danh sách banner cơ bản";
		$tt_bannerbsc2 = "Basic Banner by Category";
		$tt_banner = "Danh sách banner";
		$tt_banner_add = "Thêm banner";
		$tt_banner_edit = "Chỉnh sửa banner";
		$tt_bulletin = "Danh sách bản tin";
		$tt_bulletin_add = "Thêm bản tin";
		$tt_bulletin_edit = "Chỉnh sửa bản tin";
		$tt_bulletin_delete = "Xóa bản tin";
		$tt_bannercate = "Danh sách mục banner";
		$tt_bannercate_add = "Thêm sửa mục banner";
		$tt_bannercate_edit = "Chỉnh sửa mục banner";
		$tt_bulletincate = "Danh sách mục bản tin";
		$tt_bulletincate_add = "Thêm mục bản tin";
		$tt_bulletincate_edit = "Chỉnh sửa mục bản tin";
		$tt_expirewarning = "Cảnh báo hết hiệu lực";
		$tt_lock = "Dữ liệu đã bị khóa";

		$tm_product = "Products";
		$tt_products_manager = "Products Manager";
		$tt_products_categorys_manager = "Products Category Manager";
		$tt_fea_products_manager = "Featured Products";
		$tt_mail_products_manager = "Mail Product List";

		$product_name = "Tên sản phẩm";
		$access_report = "Thống Kê Truy Cập";
		$mapCode = "Map Code";
	}
	
	else { 
		
		$langpicjp = "lang_jp_02.png"; $langpicvn = "lang_vn_01.png"; $langpicen = "lang_en_01.png";
		$headlogo = "header_07_jp.png";
		$texttitlebar = "FACT-LINK : : ベトナムの日系製造業のためのポータルサイト";
		
		$tb_pagename = "ページ名";
		$tb_option = "オプション";
		$tb_lang = "語";
		$tb_status = "地位";
		$tb_edit = "編集";
		$tb_subject = "題名";
		$tb_date = "日付";
		
		$lb_nationality = "Company Nationality";
		$lb_njp = "Japanese";
		$lb_nvn = "Vietnamese";
		$lb_nother = "Other Nation";
		
		$lb_en = "英語";
		$lb_jp = "日本語";
		$lb_vn = "ベトナム語";
		$lb_en_full = "英語のページ";
		$lb_jp_full = "日本語のページ";
		$lb_vn_full = "ベトナム語のページ";
		$lb_back = "戻る";
		$lb_enable = "有効にする";
		$lb_status = "非表示";
		$lb_left = "左";
		$lb_right = "右";
		$lb_pag_name = "メニュー名";
		$lb_pag_pagetitle = "タイトルバー名";
		$lb_pag_sort = "ページの表示順";
		$lb_pag_textcolor = "大見出しの色";
		$lb_pag_title = "大見出し";
		$lb_pag_detail = "詳細";
		$lb_pag_image = "画像";
		$lb_pag_image_width = "横幅 (px)";
		$lb_pag_image_link = "元の画像にリンクを張る";
		$lb_pag_image_disable = "掲載の画像を削除する";
		$lb_pag_video_link = "動画のリンク";
		$lb_pag_media_option = "メディアオプション";
		$lb_pag_media_remove = "メディアを削除する";
		$lb_mem_subdesc = "会社キャッチコピー";
		$lb_mem_category = "業種";
		$lb_mem_maincategory = "メインカテゴリー";
		$lb_mem_subcategory = "サブカテゴリー";
		$lb_mem_footer = "下部欄外の帯名称";
		$lb_prf_comname = "会社名";
		$lb_prf_comname_aka = "会社名（カナ）";
		$lb_prf_pername = "代表者名";
		$lb_prf_posname = "役職";
		$lb_prf_business = "事業内容";
		$lb_prf_product = "取扱品目";
		$lb_prf_seocom = "会社の説明（検索＆SEO用）";
		$lb_prf_seokey = "キーワード（検索＆SEO用）";
		$lb_prf_addlab = "住所（見出し）";
		$lb_prf_add = "住所";
		$lb_prf_ine = "住所（工業団地）";
		$lb_prf_prv = "住所（県名）";
		$lb_prf_cty = "住所（国名）";
		$lb_prf_zip = "住所（郵便番号）";
		$lb_prf_tellab = "電話（見出し）";
		$lb_prf_tel = "電話";
		$lb_prf_maillab = "E-mail（見出し）";
		$lb_prf_mail = "E-mail";
		$lb_prf_url = "URL";
		$lb_prf_establish = "創立日";
		$lb_prf_capital = "資本金";
		$lb_prf_parent = "親会社";
		$lb_prf_share = "主要株主";
		$lb_prf_employee = "従業員数";
		$lb_prf_accdate = "決算期";
		$lb_prf_bank = "取引銀行";
		$lb_prf_valcus = "主要取引先";
		$lb_prf_conlab = "内容（見出し）";
		$lb_prf_con = "内容";
		$lb_prf_textcolor = "見出しの色";
		
		$lb_hom_keytemplate = "パネル様式";
		$lb_hom_keytitlecolor = "大見出しの色";
		$lb_hom_keytitle = "３連パネルの大見出し";
		$lb_hom_keydetail = "３連パネルの説明文";
		$lb_hom_keytitle_sub = "パネル：題名";
		$lb_hom_keydetail_sub = "パネル：文章";
		$lb_hom_linetitlecolor = "３連アピールの大見出しの色";
		$lb_hom_linetitle = "３連アピールの大見出し";
		$lb_hom_linedetail = "３連アピールの説明文";
		$lb_hom_linetitle_sub = "アピール：題名";
		$lb_hom_linedetail_sub = "アピール：文章";
		$lb_hom_lineimage = "アピール：写真";
		$lb_hom_lineimage_width = "アピール：写真横幅 (px)";
		$lb_hom_desc = "一番下の文（注記など）";
		
		$lb_con_status = "表示/非表示";
		$lb_con_pattern = "デザイン選択";
		$lb_con_title = "タイトル";
		$lb_con_subtitle = "サブタイトル";
		$lb_con_titlecolor = "タイトルの色";
		
		$lb_pst_template = "現在のテンプレート";
		$lb_pst_title = "現在のタイトル、大見出し";
		$lb_pst_title_detail = "現在の内容";
		$lb_pst_bottom = "注記タイトル";
		$lb_pst_bottom_detail = "注記内容";
		$lb_box = "現在のボックス";
		$lb_text = "テキスト様式";
		$lb_image = "画像の様式";
		
		$lb_mail_to = "宛名";
		$lb_mail_mail = "送信先 E-mail";
		$lb_mail_subject = "題名";
		$lb_mail_detail = "本文";
		$lb_mail_by = "差出人";
		$lb_mail_company = "貴社名";
		$lb_mail_department = "部署名";
		$lb_mail_contactname = "お名前";
		$lb_mail_tel = "TEL";
		$lb_mail_fax = "FAX";
		$lb_mail_email = "メールアドレス";
		$lb_mail_content = "内容";
		
		$lb_mem_contactinfo = "ご連絡情報";
		$lb_mem_id = "会員ID";
		$lb_mem_url = "会員URL";
		$lb_mem_registered = "ご登録日";
		$lb_mem_current = "現在の契約内容";
		$lb_mem_package = "パッケージ";
		
		$lb_username = "希望ユーザー名";
		$lb_password = "初期パスワード";
		$lb_password_old = "現在のパスワード";
		$lb_password_new = "新しいパスワード";
		$lb_password_confirm = "パスワード再入力";
		$lb_comname = "会社名";
		$lb_ie = "工業団地";
		$lb_address = "住所";
		$lb_province = "県名";
		$lb_country = "国名";
		$lb_zip = "郵便番号";
		$lb_comtel = "TEL";
		$lb_comfax = "FAX";
		$lb_contact = "担当者";
		$lb_position = "部署役職名";
		$lb_gender = "性別";
		$lb_mail = "ご連絡先 E-MAIL";
		$lb_tel = "ご連絡先 TEL";
		$lb_confirmcode = "認証コード";
		$lb_confirmcode_text = "表示されている４ケタの数字を入力してください。";
		$lb_male = "男性";
		$lb_female = "女性";
		$lb_register = "確認画面へ進む";
		$lb_memurl = "URL";
		$lb_memid = "会員番号";
		$lb_memtype = "会員区分";
		$lb_loginhis = "ログイン";
		$lb_tempmain = "メインテンプレート";
		$lb_maxwidth = "最大横幅";
		$lb_filetype = "ファイルタイプ";
		$lb_sup_subject = "題名";
		$lb_sup_detail = "本文";
		
		$lb_title_editor = "メンバー編集";
		$lb_title_admin = "管理編集";
		
		$lb_alt_on = "ON (OFFに切り替える)";
		$lb_alt_off = "OFF (ONに切り替える)";
		$lb_alt_edit = "編集";
		$lb_alt_expand = "追加編集";
		$lb_alt_view = "一覧";
		$lb_alt_create = "新しいページの作成";
		$lb_alt_delete = "削除";
		
		$lb_select = "----- Please Select -----";
		
		$tab_profile = "会社情報";
		$tab_home = "ホーム";
		$tab_content = "情報ページ";
		$tab_presentation = "プレゼン";
		$tab_inquiry = "お問合わせ";
		$tab_products = "PRODUCTS";

		
		$mn_info = "ユーザーの情報";
		$mn_edit = "プロファイル編集";
		$mn_pass = "パスワード変更";
		$mn_logout = "ログアウト";
		$mn_page = "ページ管理";
		$mn_template = "テンプレートの変更";
		$mn_mailin = "メール - 受信";
		$mn_mailout = "メール - 送信";
		$mn_mailnew = "メール - 作成";
		$mn_maildel = "メール - 削除";
		$mn_support = "サポートフォーム";
		$mn_main = "メインメニュー";
		$mn_mail = "メールボックス";
		$mn_help = "サポート";
		
		$mm_prf_add = "会社概要追加";
		$mm_hom_add = "ホーム追加";
		$mm_inq_add = "お問合わせ追加";
		$mm_pst_add = "プレゼンの追加";
		$mm_box_add = "プレゼンボックスの追加";
		$mm_con_add = "ページ追加";
		$mm_col_add = "サブページ追加";
		$mm_prf_edit = "会社概要編集";
		$mm_hom_edit = "ホーム編集";
		$mm_inq_edit = "お問合わせ編集";
		$mm_pst_edit = "プレゼンの編集";
		$mm_box_edit = "プレゼンボックスの編集";
		$mm_con_edit = "ページ編集";
		$mm_col_edit = "サブページ編集";
		$mm_col_delete = "サブページ削除";
		$mm_box_delete = "プレゼンボックスの削除";
		
		$me_en = "英";
		$me_jp = "日本";
		$me_vn = "ベトナム";
		$me_edit = "編集";
		$me_enable = "表示";
		$me_disable = "非表示";
		$me_page = "ページ";
		
		$bn_edit = "編集";
		
		$tx_supportsent = "お問い合わせ送信完了。";
		$tx_confirmdelete = "この内容を削除してもよろしいですか？";
		
		$tm_main = "メイン";
		$tm_top = "トップページ";
		$tm_banner = "バナー";
		$tm_member = "メンバー";
		$tm_news = "ニュース";
		$tm_contact = "連絡";
		$tm_magazine = "マガジン";
		$tm_setting = "設定";
		
		$tt_home = "ホーム";
		$tt_logout = "ログアウト";
		$tt_memberall = "会員リスト";
		$tt_memberbsc = "Basic Member List";
		$tt_memberfree = "Free Member List";
		$tt_member = "会員リスト";
		$tt_member_search = "会員検索";
		$tt_member_searchcate = "業種別会員検索";
		$tt_member_edit = "Edit Member";
		$tt_member_info = "Member Information";
		$tt_member_page = "Page Management";
		$tt_member_template = "Change Template";
		$tt_member_contract = "Edit Contract";
		$tt_member_bulcat = "Category Bulletin";
		$tt_member_onoff = "Change Status";
		$tt_member_inq = "Inquiry List";
		$tt_feature = "特集記事";
		$tt_feature_add = "Add Feature Article";
		$tt_feature_edit = "Edit Feature Article";
		$tt_feature_view = "View Feature Article";
		$tt_update = "最新情報";
		$tt_update_add = "Add Updated Info";
		$tt_update_edit = "Edit Updated Info";
		$tt_update_delete = "Delete Updated Info";
		$tt_introduce = "企業紹介(一押し企業)";
		$tt_introduce_add = "Add Introduce Company";
		$tt_introduce_edit = "Edit Introduce Company";
		$tt_introduce_set = "企業紹介設定(一押し企業)";
		$tt_introduce_set_edit = "Edit Introduce Company Set";
		$tt_news = "ニュース";
		$tt_news_add = "Add News";
		$tt_news_edit = "Edit News";
		$tt_news_delete = "Delete News";
		$tt_newsgenre = "ニュースジャンル";
		$tt_newsgenre_add = "Add News Gerne";
		$tt_newsgenre_edit = "Edit News Gerne";
		$tt_newseditor = "ニュース編集";
		$tt_newseditor_add = "Add News Editor";
		$tt_newseditor_edit = "Edit News Editor";
		$tt_category = "業種別リスト";
		$tt_category_add = "Add Category";
		$tt_category_edit = "Edit Category";
		$tt_ie = "工業団地別リスト";
		$tt_ie_add = "Add Industrial Estate";
		$tt_ie_edit = "Edit Industrial Estate";
		$tt_province = "地域別リスト";
		$tt_province_add = "Add Province";
		$tt_province_edit = "Edit Province";
		$tt_country = "国別リスト";
		$tt_country_add = "Add Country";
		$tt_country_edit = "Edit Country";
		$tt_package = "パッケージ";
		$tt_package_add = "Add Package";
		$tt_package_edit = "Edit Package";
		$tt_tempmain = "メインテンプレート";
		$tt_tempmain_add = "Add Main Template";
		$tt_tempmain_edit = "Edit Main Template";
		$tt_tempkey = "キーテンプレート";
		$tt_tempkey_add = "Add Key Template";
		$tt_tempkey_edit = "Edit Key Template";
		$tt_fontcolor = "フォントカラー";
		$tt_fontcolor_add = "Add Font Color";
		$tt_fontcolor_edit = "Edit Font Color";
		$tt_patterncon = "Content Pattern List";
		$tt_patterncon_add = "Add Content Pattern";
		$tt_patterncon_edit = "Edit Content Pattern";
		$tt_page = "Page Management";
		$tt_contact = "連絡事項";
		$tt_contact_view = "View Contact";
		$tt_magazine = "メールマガジン";
		$tt_magazine_add = "Add Mail Magazine";
		$tt_magazine_edit = "Edit Mail Magazine";
		$tt_magazine_view = "View Mail Magazine";
		$tt_bannerspccate = "業種別スペシャルバナー";
		$tt_bannerspc = "スペシャルバナー";
		$tt_bannerbsc = "ベーシックバナー";
		$tt_bannerbsc2 = "Basic Banner by Category";
		$tt_banner = "バナーレート";
		$tt_banner_add = "Add Banner";
		$tt_banner_edit = "Edit Banner";
		$tt_bulletin = "告示";
		$tt_bulletin_add = "Add Bulletin";
		$tt_bulletin_edit = "Edit Bulletin";
		$tt_bulletin_delete = "Delete Bulletin";
		$tt_bannercate = "Category Banner List";
		$tt_bannercate_add = "Add Category Banner";
		$tt_bannercate_edit = "Edit Category Banner";
		$tt_bulletincate = "Category Bulletin List";
		$tt_bulletincate_add = "Add Category Bulletin";
		$tt_bulletincate_edit = "Edit Category Bulletin";
		$tt_expirewarning = "Expire Warning";
		$tt_lock = "現在使用中";

		$tm_product = "Products";
		$tt_products_manager = "Products Manager";
		$tt_products_categorys_manager = "Products Category Manager";
		$tt_fea_products_manager = "Featured Products";
		$tt_mail_products_manager = "Mail Product List";

		$product_name = "製品名";
		$access_report = "アクセスレポート";
		$mapCode = "Map Code";
		
	} 
	
	$tpl->assign("##mapCode##", $mapCode);
	$tpl->assign("##langpicjp##", $langpicjp);
	$tpl->assign("##langpicvn##", $langpicvn);
	$tpl->assign("##langpicen##", $langpicen);
	$tpl->assign("##headlogo##", $headlogo);
	$tpl->assign("##texttitlebar##", $texttitlebar);
	$tpl->assign("##tb_pagename##", $tb_pagename);
	$tpl->assign("##tb_option##", $tb_option);
	$tpl->assign("##tb_lang##", $tb_lang);
	$tpl->assign("##tb_status##", $tb_status);
	$tpl->assign("##tb_edit##", $tb_edit);
	$tpl->assign("##tb_subject##", $tb_subject);
	$tpl->assign("##tb_date##", $tb_date);
	$tpl->assign("##lb_nationality##", $lb_nationality);
	$tpl->assign("##lb_njp##", $lb_njp);
	$tpl->assign("##lb_nvn##", $lb_nvn);
	$tpl->assign("##lb_nother##", $lb_nother);
	$tpl->assign("##lb_en##", $lb_en);
	$tpl->assign("##lb_jp##", $lb_jp);
	$tpl->assign("##lb_vn##", $lb_vn);
	$tpl->assign("##lb_en_full##", $lb_en_full);
	$tpl->assign("##lb_jp_full##", $lb_jp_full);
	$tpl->assign("##lb_vn_full##", $lb_vn_full);
	$tpl->assign("##lb_back##", $lb_back);
	$tpl->assign("##lb_enable##", $lb_enable);
	$tpl->assign("##lb_status##", $lb_status);
	$tpl->assign("##lb_left##", $lb_left);
	$tpl->assign("##lb_right##", $lb_right);
	$tpl->assign("##lb_pag_name##", $lb_pag_name);
	$tpl->assign("##lb_pag_pagetitle##", $lb_pag_pagetitle);
	$tpl->assign("##lb_pag_sort##", $lb_pag_sort);
	$tpl->assign("##lb_pag_textcolor##", $lb_pag_textcolor);
	$tpl->assign("##lb_pag_title##", $lb_pag_title);
	$tpl->assign("##lb_pag_detail##", $lb_pag_detail);
	$tpl->assign("##lb_pag_image##", $lb_pag_image);
	$tpl->assign("##lb_pag_image_width##", $lb_pag_image_width);
	$tpl->assign("##lb_pag_image_link##", $lb_pag_image_link);
	$tpl->assign("##lb_pag_image_disable##", $lb_pag_image_disable);
	$tpl->assign("##lb_pag_video_link##", $lb_pag_video_link);
	$tpl->assign("##lb_pag_media_option##", $lb_pag_media_option);
	$tpl->assign("##lb_pag_media_remove##", $lb_pag_media_remove);
	$tpl->assign("##lb_mem_subdesc##", $lb_mem_subdesc);
	$tpl->assign("##lb_mem_category##", $lb_mem_category);
	$tpl->assign("##lb_mem_maincategory##", $lb_mem_maincategory);
	$tpl->assign("##lb_mem_subcategory##", $lb_mem_subcategory);
	$tpl->assign("##lb_mem_footer##", $lb_mem_footer);
	$tpl->assign("##lb_prf_comname##", $lb_prf_comname);
	$tpl->assign("##lb_prf_comname_aka##", $lb_prf_comname_aka);
	$tpl->assign("##lb_prf_pername##", $lb_prf_pername);
	$tpl->assign("##lb_prf_posname##", $lb_prf_posname);
	$tpl->assign("##lb_prf_business##", $lb_prf_business);
	$tpl->assign("##lb_prf_product##", $lb_prf_product);
	$tpl->assign("##lb_prf_seocom##", $lb_prf_seocom);
	$tpl->assign("##lb_prf_seokey##", $lb_prf_seokey);
	$tpl->assign("##lb_prf_addlab##", $lb_prf_addlab);
	$tpl->assign("##lb_prf_add##", $lb_prf_add);
	$tpl->assign("##lb_prf_ine##", $lb_prf_ine);
	$tpl->assign("##lb_prf_prv##", $lb_prf_prv);
	$tpl->assign("##lb_prf_cty##", $lb_prf_cty);
	$tpl->assign("##lb_prf_zip##", $lb_prf_zip);
	$tpl->assign("##lb_prf_tellab##", $lb_prf_tellab);
	$tpl->assign("##lb_prf_tel##", $lb_prf_tel);
	$tpl->assign("##lb_prf_maillab##", $lb_prf_maillab);
	$tpl->assign("##lb_prf_mail##", $lb_prf_mail);
	$tpl->assign("##lb_prf_url##", $lb_prf_url);
	$tpl->assign("##lb_prf_establish##", $lb_prf_establish);
	$tpl->assign("##lb_prf_capital##", $lb_prf_capital);
	$tpl->assign("##lb_prf_parent##", $lb_prf_parent);
	$tpl->assign("##lb_prf_share##", $lb_prf_share);
	$tpl->assign("##lb_prf_employee##", $lb_prf_employee);
	$tpl->assign("##lb_prf_accdate##", $lb_prf_accdate);
	$tpl->assign("##lb_prf_bank##", $lb_prf_bank);
	$tpl->assign("##lb_prf_valcus##", $lb_prf_valcus);
	$tpl->assign("##lb_prf_conlab##", $lb_prf_conlab);
	$tpl->assign("##lb_prf_con##", $lb_prf_con);
	$tpl->assign("##lb_prf_textcolor##", $lb_prf_textcolor);
	$tpl->assign("##lb_hom_keytemplate##", $lb_hom_keytemplate);
	$tpl->assign("##lb_hom_keytitlecolor##", $lb_hom_keytitlecolor);
	$tpl->assign("##lb_hom_keytitle##", $lb_hom_keytitle);
	$tpl->assign("##lb_hom_keydetail##", $lb_hom_keydetail);
	$tpl->assign("##lb_hom_keytitle_sub##", $lb_hom_keytitle_sub);
	$tpl->assign("##lb_hom_keydetail_sub##", $lb_hom_keydetail_sub);
	$tpl->assign("##lb_hom_linetitlecolor##", $lb_hom_linetitlecolor);
	$tpl->assign("##lb_hom_linetitle##", $lb_hom_linetitle);
	$tpl->assign("##lb_hom_linedetail##", $lb_hom_linedetail);
	$tpl->assign("##lb_hom_linetitle_sub##", $lb_hom_linetitle_sub);
	$tpl->assign("##lb_hom_linedetail_sub##", $lb_hom_linedetail_sub);
	$tpl->assign("##lb_hom_lineimage##", $lb_hom_lineimage);
	$tpl->assign("##lb_hom_lineimage_width##", $lb_hom_lineimage_width);
	$tpl->assign("##lb_hom_desc##", $lb_hom_desc);
	$tpl->assign("##lb_con_status##", $lb_con_status);
	$tpl->assign("##lb_con_pattern##", $lb_con_pattern);
	$tpl->assign("##lb_con_title##", $lb_con_title);
	$tpl->assign("##lb_con_subtitle##", $lb_con_subtitle);
	$tpl->assign("##lb_con_titlecolor##", $lb_con_titlecolor);
	$tpl->assign("##lb_pst_template##", $lb_pst_template);
	$tpl->assign("##lb_pst_title##", $lb_pst_title);
	$tpl->assign("##lb_pst_title_detail##", $lb_pst_title_detail);
	$tpl->assign("##lb_pst_bottom##", $lb_pst_bottom);
	$tpl->assign("##lb_pst_bottom_detail##", $lb_pst_bottom_detail);
	$tpl->assign("##lb_box##", $lb_box);
	$tpl->assign("##lb_text##", $lb_text);
	$tpl->assign("##lb_image##", $lb_image);
	$tpl->assign("##lb_mail_to##", $lb_mail_to);
	$tpl->assign("##lb_mail_mail##", $lb_mail_mail);
	$tpl->assign("##lb_mail_subject##", $lb_mail_subject);
	$tpl->assign("##lb_mail_detail##", $lb_mail_detail);
	$tpl->assign("##lb_mail_by##", $lb_mail_by);
	$tpl->assign("##lb_mail_company##", $lb_mail_company);
	$tpl->assign("##lb_mail_department##", $lb_mail_department);
	$tpl->assign("##lb_mail_contactname##", $lb_mail_contactname);
	$tpl->assign("##lb_mail_tel##", $lb_mail_tel);
	$tpl->assign("##lb_mail_fax##", $lb_mail_fax);
	$tpl->assign("##lb_mail_email##", $lb_mail_email);
	$tpl->assign("##lb_mail_subject##", $lb_mail_subject);
	$tpl->assign("##lb_mail_content##", $lb_mail_content);
	$tpl->assign("##lb_mem_contactinfo##", $lb_mem_contactinfo);
	$tpl->assign("##lb_mem_id##", $lb_mem_id);
	$tpl->assign("##lb_mem_url##", $lb_mem_url);
	$tpl->assign("##lb_mem_registered##", $lb_mem_registered);
	$tpl->assign("##lb_mem_current##", $lb_mem_current);
	$tpl->assign("##lb_mem_package##", $lb_mem_package);
	$tpl->assign("##lb_username##", $lb_username);
	$tpl->assign("##lb_password##", $lb_password);
	$tpl->assign("##lb_password_old##", $lb_password_old);
	$tpl->assign("##lb_password_new##", $lb_password_new);
	$tpl->assign("##lb_password_confirm##", $lb_password_confirm);
	$tpl->assign("##lb_comname##", $lb_comname);
	$tpl->assign("##lb_ie##", $lb_ie);
	$tpl->assign("##lb_address##", $lb_address);
	$tpl->assign("##lb_province##", $lb_province);
	$tpl->assign("##lb_country##", $lb_country);
	$tpl->assign("##lb_zip##", $lb_zip);
	$tpl->assign("##lb_comtel##", $lb_comtel);
	$tpl->assign("##lb_comfax##", $lb_comfax);
	$tpl->assign("##lb_contact##", $lb_contact);
	$tpl->assign("##lb_position##", $lb_position);
	$tpl->assign("##lb_gender##", $lb_gender);
	$tpl->assign("##lb_mail##", $lb_mail);
	$tpl->assign("##lb_tel##", $lb_tel);
	$tpl->assign("##lb_confirmcode##", $lb_confirmcode);
	$tpl->assign("##lb_confirmcode_text##", $lb_confirmcode_text);
	$tpl->assign("##lb_male##", $lb_male);
	$tpl->assign("##lb_female##", $lb_female);
	$tpl->assign("##lb_register##", $lb_register);
	$tpl->assign("##lb_memurl##", $lb_memurl);
	$tpl->assign("##lb_memid##", $lb_memid);
	$tpl->assign("##lb_memtype##", $lb_memtype);
	$tpl->assign("##lb_loginhis##", $lb_loginhis);
	$tpl->assign("##lb_tempmain##", $lb_tempmain);
	$tpl->assign("##lb_maxwidth##", $lb_maxwidth);
	$tpl->assign("##lb_filetype##", $lb_filetype);
	$tpl->assign("##lb_sup_subject##", $lb_sup_subject);
	$tpl->assign("##lb_sup_detail##", $lb_sup_detail);
	$tpl->assign("##lb_title_editor##", $lb_title_editor);
	$tpl->assign("##lb_title_admin##", $lb_title_admin);
	$tpl->assign("##lb_alt_edit##", $lb_alt_edit);
	$tpl->assign("##lb_alt_expand##", $lb_alt_expand);
	$tpl->assign("##lb_alt_view##", $lb_alt_view);
	$tpl->assign("##lb_alt_create##", $lb_alt_create);
	$tpl->assign("##lb_alt_delete##", $lb_alt_delete);
	$tpl->assign("##lb_select##", $lb_select);
	$tpl->assign("##tab_profile##", $tab_profile);
	$tpl->assign("##tab_home##", $tab_home);
	$tpl->assign("##tab_content##", $tab_content);
	$tpl->assign("##tab_presentation##", $tab_presentation);
	$tpl->assign("##tab_inquiry##", $tab_inquiry);
	$tpl->assign("##tab_products##", $tab_products);
	$tpl->assign("##mn_info##", $mn_info);
	$tpl->assign("##mn_edit##", $mn_edit);
	$tpl->assign("##mn_pass##", $mn_pass);
	$tpl->assign("##mn_logout##", $mn_logout);
	$tpl->assign("##mn_page##", $mn_page);
	$tpl->assign("##mn_template##", $mn_template);
	$tpl->assign("##mn_mailin##", $mn_mailin);
	$tpl->assign("##mn_mailout##", $mn_mailout);
	$tpl->assign("##mn_mailnew##", $mn_mailnew);
	$tpl->assign("##mn_maildel##", $mn_maildel);
	$tpl->assign("##mn_support##", $mn_support);
	$tpl->assign("##mn_main##", $mn_main);
	$tpl->assign("##mn_mail##", $mn_mail);
	$tpl->assign("##mn_help##", $mn_help);
	$tpl->assign("##mm_prf_add##", $mm_prf_add);
	$tpl->assign("##mm_hom_add##", $mm_hom_add);
	$tpl->assign("##mm_inq_add##", $mm_inq_add);
	$tpl->assign("##mm_pst_add##", $mm_pst_add);
	$tpl->assign("##mm_box_add##", $mm_box_add);
	$tpl->assign("##mm_con_add##", $mm_con_add);
	$tpl->assign("##mm_col_add##", $mm_col_add);
	$tpl->assign("##mm_prf_edit##", $mm_prf_edit);
	$tpl->assign("##mm_hom_edit##", $mm_hom_edit);
	$tpl->assign("##mm_inq_edit##", $mm_inq_edit);
	$tpl->assign("##mm_pst_edit##", $mm_pst_edit);
	$tpl->assign("##mm_box_edit##", $mm_box_edit);
	$tpl->assign("##mm_con_edit##", $mm_con_edit);
	$tpl->assign("##mm_col_edit##", $mm_col_edit);
	$tpl->assign("##mm_col_delete##", $mm_col_delete);
	$tpl->assign("##mm_box_delete##", $mm_box_delete);
	$tpl->assign("##me_page##", $me_page);
	$tpl->assign("##bn_edit##", $bn_edit);
	$tpl->assign("##tx_supportsent##", $tx_supportsent);
	$tpl->assign("##tx_confirmdelete##", $tx_confirmdelete);
	
	$tpl->assign("##tm_main##", $tm_main);
	$tpl->assign("##tm_top##", $tm_top);
	$tpl->assign("##tm_member##", $tm_member);
	$tpl->assign("##tm_banner##", $tm_banner);
	$tpl->assign("##tm_news##", $tm_news);
	$tpl->assign("##tm_contact##", $tm_contact);
	$tpl->assign("##tm_magazine##", $tm_magazine);
	$tpl->assign("##tm_setting##", $tm_setting);
	
	$tpl->assign("##tt_category_sort##", $tt_category_sort);
	$tpl->assign("##tt_member_sort##", $tt_member_sort);
	$tpl->assign("##tt_bulletin_sort##", $tt_bulletin_sort);
	$tpl->assign("##tt_home##", $tt_home);
	$tpl->assign("##tt_logout##", $tt_logout);
	$tpl->assign("##tt_memberall##", $tt_memberall);
	$tpl->assign("##tt_memberbsc##", $tt_memberbsc);
	$tpl->assign("##tt_memberfree##", $tt_memberfree);
	$tpl->assign("##tt_member##", $tt_member);
	$tpl->assign("##tt_member_search##", $tt_member_search);
	$tpl->assign("##tt_member_searchcate##", $tt_member_searchcate);
	$tpl->assign("##tt_member_edit##", $tt_member_edit);
	$tpl->assign("##tt_member_info##", $tt_member_info);
	$tpl->assign("##tt_member_page##", $tt_member_page);
	$tpl->assign("##tt_member_template##", $tt_member_template);
	$tpl->assign("##tt_member_contract##", $tt_member_contract);
	$tpl->assign("##tt_member_bulcat##", $tt_member_bulcat);
	$tpl->assign("##tt_member_onoff##", $tt_member_onoff);
	$tpl->assign("##tt_feature##", $tt_feature);
	$tpl->assign("##tt_feature_add##", $tt_feature_add);
	$tpl->assign("##tt_feature_edit##", $tt_feature_edit);
	$tpl->assign("##tt_feature_view##", $tt_feature_view);
	$tpl->assign("##tt_update##", $tt_update);
	$tpl->assign("##tt_update_add##", $tt_update_add);
	$tpl->assign("##tt_update_edit##", $tt_update_edit);
	$tpl->assign("##tt_update_delete##", $tt_update_delete);
	$tpl->assign("##tt_introduce##", $tt_introduce);
	$tpl->assign("##tt_introduce_add##", $tt_introduce_add);
	$tpl->assign("##tt_introduce_edit##", $tt_introduce_edit);
	$tpl->assign("##tt_introduce_set##", $tt_introduce_set);
	$tpl->assign("##tt_introduce_set_edit##", $tt_introduce_set_edit);
	$tpl->assign("##tt_news##", $tt_news);
	$tpl->assign("##tt_news_add##", $tt_news_add);
	$tpl->assign("##tt_news_edit##", $tt_news_edit);
	$tpl->assign("##tt_news_delete##", $tt_news_delete);
	$tpl->assign("##tt_newsgenre##", $tt_newsgenre);
	$tpl->assign("##tt_newsgenre_add##", $tt_newsgenre_add);
	$tpl->assign("##tt_newsgenre_edit##", $tt_newsgenre_edit);
	$tpl->assign("##tt_newseditor##", $tt_newseditor);
	$tpl->assign("##tt_newseditor_add##", $tt_newseditor_add);
	$tpl->assign("##tt_newseditor_edit##", $tt_newseditor_edit);
	$tpl->assign("##tt_category##", $tt_category);
	$tpl->assign("##tt_category_add##", $tt_category_add);
	$tpl->assign("##tt_category_edit##", $tt_category_edit);
	$tpl->assign("##tt_ie##", $tt_ie);
	$tpl->assign("##tt_ie_add##", $tt_ie_add);
	$tpl->assign("##tt_ie_edit##", $tt_ie_edit);
	$tpl->assign("##tt_province##", $tt_province);
	$tpl->assign("##tt_province_add##", $tt_province_add);
	$tpl->assign("##tt_province_edit##", $tt_province_edit);
	$tpl->assign("##tt_country##", $tt_country);
	$tpl->assign("##tt_country_add##", $tt_country_add);
	$tpl->assign("##tt_country_edit##", $tt_country_edit);
	$tpl->assign("##tt_package##", $tt_package);
	$tpl->assign("##tt_package_add##", $tt_package_add);
	$tpl->assign("##tt_package_edit##", $tt_package_edit);
	$tpl->assign("##tt_tempmain##", $tt_tempmain);
	$tpl->assign("##tt_tempmain_add##", $tt_tempmain_add);
	$tpl->assign("##tt_tempmain_edit##", $tt_tempmain_edit);
	$tpl->assign("##tt_tempkey##", $tt_tempkey);
	$tpl->assign("##tt_tempkey_add##", $tt_tempkey_add);
	$tpl->assign("##tt_tempkey_edit##", $tt_tempkey_edit);
	$tpl->assign("##tt_fontcolor##", $tt_fontcolor);
	$tpl->assign("##tt_fontcolor_add##", $tt_fontcolor_add);
	$tpl->assign("##tt_fontcolor_edit##", $tt_fontcolor_edit);
	$tpl->assign("##tt_patterncon##", $tt_patterncon);
	$tpl->assign("##tt_patterncon_add##", $tt_patterncon_add);
	$tpl->assign("##tt_patterncon_edit##", $tt_patterncon_edit);
	$tpl->assign("##tt_page##", $tt_page);
	$tpl->assign("##tt_contact##", $tt_contact);
	$tpl->assign("##tt_contact_view##", $tt_contact_view);
	$tpl->assign("##tt_magazine##", $tt_magazine);
	$tpl->assign("##tt_magazine_add##", $tt_magazine_add);
	$tpl->assign("##tt_magazine_edit##", $tt_magazine_edit);
	$tpl->assign("##tt_magazine_view##", $tt_magazine_view);
	$tpl->assign("##tt_bannerspccate##", $tt_bannerspccate);
	$tpl->assign("##tt_bannerspc##", $tt_bannerspc);
	$tpl->assign("##tt_bannerbsc##", $tt_bannerbsc);
	$tpl->assign("##tt_bannerbsc2##", $tt_bannerbsc2);
	$tpl->assign("##tt_banner##", $tt_banner);
	$tpl->assign("##tt_banner_add##", $tt_banner_add);
	$tpl->assign("##tt_banner_edit##", $tt_banner_edit);
	$tpl->assign("##tt_bulletin##", $tt_bulletin);
	$tpl->assign("##tt_bulletin_add##", $tt_bulletin_add);
	$tpl->assign("##tt_bulletin_edit##", $tt_bulletin_edit);
	$tpl->assign("##tt_bulletin_delete##", $tt_bulletin_delete);
	$tpl->assign("##tt_bannercate##", $tt_bannercate);
	$tpl->assign("##tt_bannercate_add##", $tt_bannercate_add);
	$tpl->assign("##tt_bannercate_edit##", $tt_bannercate_edit);
	$tpl->assign("##tt_bulletincate##", $tt_bulletincate);
	$tpl->assign("##tt_bulletincate_add##", $tt_bulletincate_add);
	$tpl->assign("##tt_bulletincate_edit##", $tt_bulletincate_edit);
	$tpl->assign("##tt_expirewarning##", $tt_expirewarning);
	$tpl->assign("##tt_lock##", $tt_lock);

	$tpl->assign("##tm_product##", $tm_product);
	$tpl->assign("##tt_products_manager##", $tt_products_manager);
	$tpl->assign("##tt_products_categorys_manager##", $tt_products_categorys_manager);
	$tpl->assign("##tt_fea_products_manager##", $tt_fea_products_manager);
	$tpl->assign("##tt_mail_products_manager##", $tt_mail_products_manager);

	$tpl->assign("##product_name##", $product_name);
	$tpl->assign("##access_report##", $access_report);
	
	
	
	// Default template
	$defaultmemid = $memid;
	$sqldefault = "select * from flc_member where mem_id = '$defaultmemid';";
	$resultdefault = mysql_query($sqldefault);
	while ($dbarrdefault = mysql_fetch_array($resultdefault)) { 
		
		$defaulttpmid = $dbarrdefault['mem_template'];
		
		$sqldefault1 = "select * from flc_template_main where tpm_id = '$defaulttpmid';";
		$resultdefault1 = mysql_query($sqldefault1);
		while ($dbarrdefault1 = mysql_fetch_array($resultdefault1)) { $defaulttpkid = $dbarrdefault1['tpk_id']; $defaultclfid = $dbarrdefault1['clf_id']; }
		
	}
	
	// Mail - Inbox
	$countinbox = 0;
	$inboxmemid = $_SESSION['vmd'];
	
	$sqlinbox = "select * from flc_mail where mem_id = '$inboxmemid' and mal_box = 'i' and mal_status = 'n';";
	$resultinbox = mysql_query($sqlinbox);
	$countinbox = mysql_num_rows($resultinbox);
	
	if ($countinbox != 0) { $inboxnew = "(".$countinbox.")"; } else { $inboxnew = ""; }
	
	$tpl->assign("##inboxnew##", $inboxnew);
	
?>